/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Net.Http;
using Microsoft.Extensions.DependencyInjection;
using MailChannels.EmailApi.Api;
using MailChannels.EmailApi.Model;

namespace MailChannels.EmailApi.Client
{
    /// <summary>
    /// Provides hosting configuration for MailChannels.EmailApi
    /// </summary>
    public partial class HostConfiguration
    {
        private readonly IServiceCollection _services;
        private readonly JsonSerializerOptions _jsonOptions = new JsonSerializerOptions();

        internal bool HttpClientsAdded { get; private set; }

        /// <summary>
        /// Instantiates the class 
        /// </summary>
        /// <param name="services"></param>
        public HostConfiguration(IServiceCollection services)
        {
            _services = services;
            _jsonOptions.Converters.Add(new JsonStringEnumConverter());
            _jsonOptions.Converters.Add(new DateTimeJsonConverter());
            _jsonOptions.Converters.Add(new DateTimeNullableJsonConverter());
            _jsonOptions.Converters.Add(new DateOnlyJsonConverter());
            _jsonOptions.Converters.Add(new DateOnlyNullableJsonConverter());
            _jsonOptions.Converters.Add(new APIKeyJsonConverter());
            _jsonOptions.Converters.Add(new AsyncSendResponseJsonConverter());
            _jsonOptions.Converters.Add(new AttachmentJsonConverter());
            _jsonOptions.Converters.Add(new CheckDomainBodyJsonConverter());
            _jsonOptions.Converters.Add(new CheckDomainResultJsonConverter());
            _jsonOptions.Converters.Add(new CheckResultsJsonConverter());
            _jsonOptions.Converters.Add(new ContentItemJsonConverter());
            _jsonOptions.Converters.Add(new CustomTrackingDomainJsonConverter());
            _jsonOptions.Converters.Add(new CustomTrackingDomainListResponseJsonConverter());
            _jsonOptions.Converters.Add(new DKIMDnsRecordJsonConverter());
            _jsonOptions.Converters.Add(new DKIMKeyInfoJsonConverter());
            _jsonOptions.Converters.Add(new DKIMKeyListJsonConverter());
            _jsonOptions.Converters.Add(new DKIMKeyPairCreateRequestJsonConverter());
            _jsonOptions.Converters.Add(new DKIMKeyPairUpdateRequestJsonConverter());
            _jsonOptions.Converters.Add(new DKIMKeyRotateRequestJsonConverter());
            _jsonOptions.Converters.Add(new DKIMKeyRotateResponseJsonConverter());
            _jsonOptions.Converters.Add(new DkimResultJsonConverter());
            _jsonOptions.Converters.Add(new DkimSettingJsonConverter());
            _jsonOptions.Converters.Add(new DnsSetupRequiredJsonConverter());
            _jsonOptions.Converters.Add(new EmailAddressJsonConverter());
            _jsonOptions.Converters.Add(new ErrorResponseJsonConverter());
            _jsonOptions.Converters.Add(new KeyJsonConverter());
            _jsonOptions.Converters.Add(new LimitJsonConverter());
            _jsonOptions.Converters.Add(new LimitInputJsonConverter());
            _jsonOptions.Converters.Add(new LimitUpdateResultJsonConverter());
            _jsonOptions.Converters.Add(new LockdownResultJsonConverter());
            _jsonOptions.Converters.Add(new MailSendBodyJsonConverter());
            _jsonOptions.Converters.Add(new MailSendBodyTrackingSettingsJsonConverter());
            _jsonOptions.Converters.Add(new MailSendBodyTrackingSettingsClickTrackingJsonConverter());
            _jsonOptions.Converters.Add(new MailSendBodyTrackingSettingsOpenTrackingJsonConverter());
            _jsonOptions.Converters.Add(new MailSendBodyUnsubscribeSettingsJsonConverter());
            _jsonOptions.Converters.Add(new MessageJsonConverter());
            _jsonOptions.Converters.Add(new MetricsBucketJsonConverter());
            _jsonOptions.Converters.Add(new MetricsEngagementJsonConverter());
            _jsonOptions.Converters.Add(new MetricsEngagementBucketsJsonConverter());
            _jsonOptions.Converters.Add(new MetricsPerformanceJsonConverter());
            _jsonOptions.Converters.Add(new MetricsPerformanceBucketsJsonConverter());
            _jsonOptions.Converters.Add(new MetricsRecipientBehaviourJsonConverter());
            _jsonOptions.Converters.Add(new MetricsRecipientBehaviourBucketsJsonConverter());
            _jsonOptions.Converters.Add(new MetricsSenderJsonConverter());
            _jsonOptions.Converters.Add(new MetricsSenderResponseJsonConverter());
            _jsonOptions.Converters.Add(new MetricsVolumeJsonConverter());
            _jsonOptions.Converters.Add(new MetricsVolumeBucketsJsonConverter());
            _jsonOptions.Converters.Add(new NewKeyJsonConverter());
            _jsonOptions.Converters.Add(new PatchCustomTrackingDomainRequestJsonConverter());
            _jsonOptions.Converters.Add(new PersonalizationJsonConverter());
            _jsonOptions.Converters.Add(new PostCustomTrackingDomainRequestJsonConverter());
            _jsonOptions.Converters.Add(new SMTPPasswordJsonConverter());
            _jsonOptions.Converters.Add(new SendResultJsonConverter());
            _jsonOptions.Converters.Add(new SendResultsJsonConverter());
            _jsonOptions.Converters.Add(new SenderDomainResultJsonConverter());
            _jsonOptions.Converters.Add(new SenderDomainResultAJsonConverter());
            _jsonOptions.Converters.Add(new SenderDomainResultMxJsonConverter());
            _jsonOptions.Converters.Add(new SpfResultJsonConverter());
            _jsonOptions.Converters.Add(new SubAccountDataJsonConverter());
            _jsonOptions.Converters.Add(new SubAccountDetailsJsonConverter());
            _jsonOptions.Converters.Add(new SuppressionEntryJsonConverter());
            _jsonOptions.Converters.Add(new SuppressionEntryResponseJsonConverter());
            _jsonOptions.Converters.Add(new SuppressionListInputJsonConverter());
            _jsonOptions.Converters.Add(new SuppressionListResponseJsonConverter());
            _jsonOptions.Converters.Add(new UsageStatsJsonConverter());
            _jsonOptions.Converters.Add(new WebhookJsonConverter());
            _jsonOptions.Converters.Add(new WebhookBatchJsonConverter());
            _jsonOptions.Converters.Add(new WebhookBatchDurationJsonConverter());
            _jsonOptions.Converters.Add(new WebhookBatchResultJsonConverter());
            _jsonOptions.Converters.Add(new WebhookResendResponseJsonConverter());
            _jsonOptions.Converters.Add(new WebhookResponseJsonConverter());
            _jsonOptions.Converters.Add(new WebhookValidationRequestBodyJsonConverter());
            _jsonOptions.Converters.Add(new WebhookValidationResultJsonConverter());
            _jsonOptions.Converters.Add(new WebhookValidationResultsJsonConverter());
            JsonSerializerOptionsProvider jsonSerializerOptionsProvider = new(_jsonOptions);
            _services.AddSingleton(jsonSerializerOptionsProvider);
            _services.AddSingleton<IApiFactory, ApiFactory>();
            _services.AddSingleton<CustomTrackingApiEvents>();
            _services.AddSingleton<DKIMApiEvents>();
            _services.AddSingleton<MetricsApiEvents>();
            _services.AddSingleton<SendApiEvents>();
            _services.AddSingleton<SubAccountsApiEvents>();
            _services.AddSingleton<SuppressionApiEvents>();
            _services.AddSingleton<UsageApiEvents>();
            _services.AddSingleton<WebhooksApiEvents>();
            OnHostConfigurationCreated();
        }

        /// <summary>
        /// Configures the HttpClients.
        /// </summary>
        /// <param name="builder"></param>
        /// <returns></returns>
        public HostConfiguration AddApiHttpClients(Action<IHttpClientBuilder>? builder = null)
        {
            return AddApiHttpClients((Action<IServiceProvider, HttpClient>?)null, builder);
        }

        /// <summary>
        /// Configures the HttpClients.
        /// </summary>
        /// <param name="client"></param>
        /// <param name="builder"></param>
        /// <returns></returns>
        public HostConfiguration AddApiHttpClients(
            Action<HttpClient>? client,
            Action<IHttpClientBuilder>? builder = null)
        {
            var wrapped = client != null ? new Action<IServiceProvider, HttpClient>((_, httpClient) =>
            {
                client(httpClient);
            }) : null;
            return AddApiHttpClients(wrapped, builder);
        }

        /// <summary>
        /// Configures the HttpClients.
        /// </summary>
        /// <param name="client"></param>
        /// <param name="builder"></param>
        /// <returns></returns>
        public HostConfiguration AddApiHttpClients(
            Action<IServiceProvider, HttpClient>? client,
            Action<IHttpClientBuilder>? builder = null)
        {
            if (client == null)
                client = (_, c) => c.BaseAddress = new Uri(ClientUtils.BASE_ADDRESS);

            List<IHttpClientBuilder> builders = new List<IHttpClientBuilder>();

            builders.Add(_services.AddHttpClient<ICustomTrackingApi, CustomTrackingApi>("MailChannels.EmailApi.Api.ICustomTrackingApi", client));
            builders.Add(_services.AddHttpClient<IDKIMApi, DKIMApi>("MailChannels.EmailApi.Api.IDKIMApi", client));
            builders.Add(_services.AddHttpClient<IMetricsApi, MetricsApi>("MailChannels.EmailApi.Api.IMetricsApi", client));
            builders.Add(_services.AddHttpClient<ISendApi, SendApi>("MailChannels.EmailApi.Api.ISendApi", client));
            builders.Add(_services.AddHttpClient<ISubAccountsApi, SubAccountsApi>("MailChannels.EmailApi.Api.ISubAccountsApi", client));
            builders.Add(_services.AddHttpClient<ISuppressionApi, SuppressionApi>("MailChannels.EmailApi.Api.ISuppressionApi", client));
            builders.Add(_services.AddHttpClient<IUsageApi, UsageApi>("MailChannels.EmailApi.Api.IUsageApi", client));
            builders.Add(_services.AddHttpClient<IWebhooksApi, WebhooksApi>("MailChannels.EmailApi.Api.IWebhooksApi", client));

            foreach (IHttpClientBuilder instance in builders)
            {
                bool suppressDefault = false;
                OnAddApiHttpClientBuilder(instance, builder, ref suppressDefault);
                if (!suppressDefault)
                    builder?.Invoke(instance);
            }

            HttpClientsAdded = true;

            return this;
        }

        /// <summary>
        /// Applies configuration to each HttpClient.
        /// Implement this partial method to prepend configuration, invoke <paramref name="userBuilder"/> at the
        /// desired position, and append further configuration. Set <paramref name="suppressDefault"/> to
        /// <c>true</c> when you invoke <paramref name="userBuilder"/> yourself to prevent a second invocation,
        /// or to ignore the user's builder entirely.
        /// If this method is not implemented, <paramref name="userBuilder"/> is invoked automatically.
        /// </summary>
        /// <param name="builder">The <see cref="IHttpClientBuilder"/> to configure.</param>
        /// <param name="userBuilder">The caller-supplied builder action, or <c>null</c> if none was provided.</param>
        /// <param name="suppressDefault">Set to <c>true</c> to prevent the default invocation of <paramref name="userBuilder"/>.</param>
        partial void OnAddApiHttpClientBuilder(IHttpClientBuilder builder, Action<IHttpClientBuilder>? userBuilder, ref bool suppressDefault);

        /// <summary>
        /// Called at the end of the constructor after all JSON converters and services are registered.
        /// Implement this partial method to further configure <c>_jsonOptions</c> or register additional singletons via <c>_services</c>.
        /// </summary>
        partial void OnHostConfigurationCreated();

        /// <summary>
        /// Called after all services have been registered.
        /// Implement this partial method to register additional services.
        /// </summary>
        /// <param name="services"></param>
        partial void OnServicesAdded(IServiceCollection services);

        internal void NotifyServicesAdded(IServiceCollection services) => OnServicesAdded(services);

        /// <summary>
        /// Configures the JsonSerializerSettings
        /// </summary>
        /// <param name="options"></param>
        /// <returns></returns>
        public HostConfiguration ConfigureJsonOptions(Action<JsonSerializerOptions> options)
        {
            options(_jsonOptions);

            return this;
        }

        /// <summary>
        /// Adds tokens to your IServiceCollection
        /// </summary>
        /// <typeparam name="TTokenBase"></typeparam>
        /// <param name="token"></param>
        /// <returns></returns>
        public HostConfiguration AddTokens<TTokenBase>(TTokenBase token) where TTokenBase : TokenBase
        {
            return AddTokens(new TTokenBase[]{ token });
        }

        /// <summary>
        /// Adds tokens to your IServiceCollection
        /// </summary>
        /// <typeparam name="TTokenBase"></typeparam>
        /// <param name="tokens"></param>
        /// <returns></returns>
        public HostConfiguration AddTokens<TTokenBase>(IEnumerable<TTokenBase> tokens) where TTokenBase : TokenBase
        {
            TokenContainer<TTokenBase> container = new TokenContainer<TTokenBase>(tokens);
            _services.AddSingleton(services => container);

            return this;
        }

        /// <summary>
        /// Adds a token provider to your IServiceCollection
        /// </summary>
        /// <typeparam name="TTokenProvider"></typeparam>
        /// <typeparam name="TTokenBase"></typeparam>
        /// <returns></returns>
        public HostConfiguration UseProvider<TTokenProvider, TTokenBase>() 
            where TTokenProvider : TokenProvider<TTokenBase>
            where TTokenBase : TokenBase
        {
            _services.AddSingleton<TTokenProvider>();
            _services.AddSingleton<TokenProvider<TTokenBase>>(services => services.GetRequiredService<TTokenProvider>());

            return this;
        }
    }
}
