// <auto-generated>
/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System.Text.Json;

namespace MailChannels.EmailApi.Client
{
    /// <summary>
    /// Provides the JsonSerializerOptions
    /// </summary>
    public class JsonSerializerOptionsProvider
    {
        /// <summary>
        /// the JsonSerializerOptions
        /// </summary>
        public JsonSerializerOptions Options { get; }

        /// <summary>
        /// Instantiates a JsonSerializerOptionsProvider
        /// </summary>
        public JsonSerializerOptionsProvider(JsonSerializerOptions options)
        {
            Options = options;
        }
    }
}
