// <auto-generated>
/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MailChannels.EmailApi.Client;

namespace MailChannels.EmailApi.Model
{
    /// <summary>
    /// CheckResults
    /// </summary>
    public partial class CheckResults : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CheckResults" /> class.
        /// </summary>
        /// <param name="dkim">dkim</param>
        /// <param name="domainLockdown">domainLockdown</param>
        /// <param name="senderDomain">senderDomain</param>
        /// <param name="spf">spf</param>
        [JsonConstructor]
        public CheckResults(Option<List<DkimResult>?> dkim = default, Option<LockdownResult?> domainLockdown = default, Option<SenderDomainResult?> senderDomain = default, Option<SpfResult?> spf = default)
        {
            DkimOption = dkim;
            DomainLockdownOption = domainLockdown;
            SenderDomainOption = senderDomain;
            SpfOption = spf;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Dkim
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<DkimResult>?> DkimOption { get; private set; }

        /// <summary>
        /// Gets or Sets Dkim
        /// </summary>
        [JsonPropertyName("dkim")]
        public List<DkimResult>? Dkim { get { return this.DkimOption.Value; } set { this.DkimOption = new(value); } }

        /// <summary>
        /// Used to track the state of DomainLockdown
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<LockdownResult?> DomainLockdownOption { get; private set; }

        /// <summary>
        /// Gets or Sets DomainLockdown
        /// </summary>
        [JsonPropertyName("domain_lockdown")]
        public LockdownResult? DomainLockdown { get { return this.DomainLockdownOption.Value; } set { this.DomainLockdownOption = new(value); } }

        /// <summary>
        /// Used to track the state of SenderDomain
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<SenderDomainResult?> SenderDomainOption { get; private set; }

        /// <summary>
        /// Gets or Sets SenderDomain
        /// </summary>
        [JsonPropertyName("sender_domain")]
        public SenderDomainResult? SenderDomain { get { return this.SenderDomainOption.Value; } set { this.SenderDomainOption = new(value); } }

        /// <summary>
        /// Used to track the state of Spf
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<SpfResult?> SpfOption { get; private set; }

        /// <summary>
        /// Gets or Sets Spf
        /// </summary>
        [JsonPropertyName("spf")]
        public SpfResult? Spf { get { return this.SpfOption.Value; } set { this.SpfOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            return "CheckResults { [REDACTED] }";
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CheckResults" />
    /// </summary>
    public partial class CheckResultsJsonConverter : JsonConverter<CheckResults>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="CheckResultsJsonConverter" /> class.
        /// </summary>
        public CheckResultsJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="CheckResults" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CheckResults Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<DkimResult>?> dkim = default;
            Option<LockdownResult?> domainLockdown = default;
            Option<SenderDomainResult?> senderDomain = default;
            Option<SpfResult?> spf = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "dkim":
                            dkim = new Option<List<DkimResult>?>(JsonSerializer.Deserialize<List<DkimResult>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "domain_lockdown":
                            domainLockdown = new Option<LockdownResult?>(JsonSerializer.Deserialize<LockdownResult>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "sender_domain":
                            senderDomain = new Option<SenderDomainResult?>(JsonSerializer.Deserialize<SenderDomainResult>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "spf":
                            spf = new Option<SpfResult?>(JsonSerializer.Deserialize<SpfResult>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (dkim.IsSet && dkim.Value == null)
                throw new JsonException("Property is not nullable for class CheckResults: dkim.");

            if (domainLockdown.IsSet && domainLockdown.Value == null)
                throw new JsonException("Property is not nullable for class CheckResults: domain_lockdown.");

            if (senderDomain.IsSet && senderDomain.Value == null)
                throw new JsonException("Property is not nullable for class CheckResults: sender_domain.");

            if (spf.IsSet && spf.Value == null)
                throw new JsonException("Property is not nullable for class CheckResults: spf.");

            return new CheckResults(dkim, domainLockdown, senderDomain, spf);
        }

        /// <summary>
        /// Serializes a <see cref="CheckResults" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="checkResults"></param>
        /// <param name="jsonSerializerOptions"></param>
        public override void Write(Utf8JsonWriter writer, CheckResults checkResults, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, checkResults, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CheckResults" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="checkResults"></param>
        /// <param name="jsonSerializerOptions"></param>
        public void WriteProperties(Utf8JsonWriter writer, CheckResults checkResults, JsonSerializerOptions jsonSerializerOptions)
        {
            if (checkResults.DkimOption.IsSet && checkResults.Dkim == null)
                throw new JsonException("Cannot write null property CheckResults.Dkim to non-nullable JSON property 'dkim'.");

            if (checkResults.DomainLockdownOption.IsSet && checkResults.DomainLockdown == null)
                throw new JsonException("Cannot write null property CheckResults.DomainLockdown to non-nullable JSON property 'domain_lockdown'.");

            if (checkResults.SenderDomainOption.IsSet && checkResults.SenderDomain == null)
                throw new JsonException("Cannot write null property CheckResults.SenderDomain to non-nullable JSON property 'sender_domain'.");

            if (checkResults.SpfOption.IsSet && checkResults.Spf == null)
                throw new JsonException("Cannot write null property CheckResults.Spf to non-nullable JSON property 'spf'.");

            if (checkResults.DkimOption.IsSet)
            {
                writer.WritePropertyName("dkim");
                JsonSerializer.Serialize(writer, checkResults.Dkim, jsonSerializerOptions);
            }
            if (checkResults.DomainLockdownOption.IsSet)
            {
                writer.WritePropertyName("domain_lockdown");
                JsonSerializer.Serialize(writer, checkResults.DomainLockdown, jsonSerializerOptions);
            }
            if (checkResults.SenderDomainOption.IsSet)
            {
                writer.WritePropertyName("sender_domain");
                JsonSerializer.Serialize(writer, checkResults.SenderDomain, jsonSerializerOptions);
            }
            if (checkResults.SpfOption.IsSet)
            {
                writer.WritePropertyName("spf");
                JsonSerializer.Serialize(writer, checkResults.Spf, jsonSerializerOptions);
            }
        }
    }
}
