// <auto-generated>
/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MailChannels.EmailApi.Client;

namespace MailChannels.EmailApi.Model
{
    /// <summary>
    /// CheckDomainResult
    /// </summary>
    public partial class CheckDomainResult : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CheckDomainResult" /> class.
        /// </summary>
        /// <param name="checkResults">checkResults</param>
        /// <param name="references">Link to SPF, Domain Lockdown or DKIM references, displayed if any verdict is not passed.</param>
        [JsonConstructor]
        public CheckDomainResult(Option<CheckResults?> checkResults = default, Option<List<string>?> references = default)
        {
            CheckResultsOption = checkResults;
            ReferencesOption = references;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of CheckResults
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<CheckResults?> CheckResultsOption { get; private set; }

        /// <summary>
        /// Gets or Sets CheckResults
        /// </summary>
        [JsonPropertyName("check_results")]
        public CheckResults? CheckResults { get { return this.CheckResultsOption.Value; } set { this.CheckResultsOption = new(value); } }

        /// <summary>
        /// Used to track the state of References
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> ReferencesOption { get; private set; }

        /// <summary>
        /// Link to SPF, Domain Lockdown or DKIM references, displayed if any verdict is not passed.
        /// </summary>
        /// <value>Link to SPF, Domain Lockdown or DKIM references, displayed if any verdict is not passed.</value>
        [JsonPropertyName("references")]
        public List<string>? References { get { return this.ReferencesOption.Value; } set { this.ReferencesOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            return "CheckDomainResult { [REDACTED] }";
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CheckDomainResult" />
    /// </summary>
    public partial class CheckDomainResultJsonConverter : JsonConverter<CheckDomainResult>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="CheckDomainResultJsonConverter" /> class.
        /// </summary>
        public CheckDomainResultJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="CheckDomainResult" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CheckDomainResult Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<CheckResults?> checkResults = default;
            Option<List<string>?> references = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "check_results":
                            checkResults = new Option<CheckResults?>(JsonSerializer.Deserialize<CheckResults>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "references":
                            references = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (checkResults.IsSet && checkResults.Value == null)
                throw new JsonException("Property is not nullable for class CheckDomainResult: check_results.");

            if (references.IsSet && references.Value == null)
                throw new JsonException("Property is not nullable for class CheckDomainResult: references.");

            return new CheckDomainResult(checkResults, references);
        }

        /// <summary>
        /// Serializes a <see cref="CheckDomainResult" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="checkDomainResult"></param>
        /// <param name="jsonSerializerOptions"></param>
        public override void Write(Utf8JsonWriter writer, CheckDomainResult checkDomainResult, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, checkDomainResult, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CheckDomainResult" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="checkDomainResult"></param>
        /// <param name="jsonSerializerOptions"></param>
        public void WriteProperties(Utf8JsonWriter writer, CheckDomainResult checkDomainResult, JsonSerializerOptions jsonSerializerOptions)
        {
            if (checkDomainResult.CheckResultsOption.IsSet && checkDomainResult.CheckResults == null)
                throw new JsonException("Cannot write null property CheckDomainResult.CheckResults to non-nullable JSON property 'check_results'.");

            if (checkDomainResult.ReferencesOption.IsSet && checkDomainResult.References == null)
                throw new JsonException("Cannot write null property CheckDomainResult.References to non-nullable JSON property 'references'.");

            if (checkDomainResult.CheckResultsOption.IsSet)
            {
                writer.WritePropertyName("check_results");
                JsonSerializer.Serialize(writer, checkDomainResult.CheckResults, jsonSerializerOptions);
            }
            if (checkDomainResult.ReferencesOption.IsSet)
            {
                writer.WritePropertyName("references");
                JsonSerializer.Serialize(writer, checkDomainResult.References, jsonSerializerOptions);
            }
        }
    }
}
