// <auto-generated>
/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MailChannels.EmailApi.Client;

namespace MailChannels.EmailApi.Model
{
    /// <summary>
    /// ContentItem
    /// </summary>
    public partial class ContentItem : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ContentItem" /> class.
        /// </summary>
        /// <param name="type">The mime type of the content you are including in your email</param>
        /// <param name="value">The actual content of the specified mime type that you are including in the message</param>
        /// <param name="templateType">The template type of the content</param>
        [JsonConstructor]
        public ContentItem(string type, string value, Option<TemplateTypeEnum?> templateType = default)
        {
            Type = type;
            Value = value;
            TemplateTypeOption = templateType;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The template type of the content
        /// </summary>
        /// <value>The template type of the content</value>
        public enum TemplateTypeEnum
        {
            /// <summary>
            /// Enum Mustache for value: mustache
            /// </summary>
            Mustache = 1
        }

        /// <summary>
        /// Returns a <see cref="TemplateTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static TemplateTypeEnum TemplateTypeEnumFromString(string value)
        {
            if (value.Equals("mustache"))
                return TemplateTypeEnum.Mustache;

            throw new NotImplementedException($"Could not convert value to type TemplateTypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="TemplateTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static TemplateTypeEnum? TemplateTypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("mustache"))
                return TemplateTypeEnum.Mustache;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="TemplateTypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string TemplateTypeEnumToJsonValue(TemplateTypeEnum? value)
        {
            if (value == TemplateTypeEnum.Mustache)
                return "mustache";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of TemplateType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<TemplateTypeEnum?> TemplateTypeOption { get; private set; }

        /// <summary>
        /// The template type of the content
        /// </summary>
        /// <value>The template type of the content</value>
        [JsonPropertyName("template_type")]
        public TemplateTypeEnum? TemplateType { get { return this.TemplateTypeOption.Value; } set { this.TemplateTypeOption = new(value); } }

        /// <summary>
        /// The mime type of the content you are including in your email
        /// </summary>
        /// <value>The mime type of the content you are including in your email</value>
        [JsonPropertyName("type")]
        public string Type { get; set; }

        /// <summary>
        /// The actual content of the specified mime type that you are including in the message
        /// </summary>
        /// <value>The actual content of the specified mime type that you are including in the message</value>
        [JsonPropertyName("value")]
        public string Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            return "ContentItem { [REDACTED] }";
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ContentItem" />
    /// </summary>
    public partial class ContentItemJsonConverter : JsonConverter<ContentItem>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="ContentItemJsonConverter" /> class.
        /// </summary>
        public ContentItemJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="ContentItem" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ContentItem Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> type = default;
            Option<string?> value = default;
            Option<ContentItem.TemplateTypeEnum?> templateType = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "type":
                            type = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "value":
                            value = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "template_type":
                            string? templateTypeRawValue = utf8JsonReader.GetString();
                            if (templateTypeRawValue != null)
                            {
                                ContentItem.TemplateTypeEnum? templateTypeValue = ContentItem.TemplateTypeEnumFromStringOrDefault(templateTypeRawValue);
                                if (templateTypeValue == null)
                                    throw new JsonException();
                                templateType = new Option<ContentItem.TemplateTypeEnum?>(templateTypeValue);
                            }
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!type.IsSet)
                throw new JsonException("Property is required for class ContentItem: type.");

            if (!value.IsSet)
                throw new JsonException("Property is required for class ContentItem: value.");

            if (type.IsSet && type.Value == null)
                throw new JsonException("Property is not nullable for class ContentItem: type.");

            if (value.IsSet && value.Value == null)
                throw new JsonException("Property is not nullable for class ContentItem: value.");

            if (templateType.IsSet && templateType.Value == null)
                throw new JsonException("Property is not nullable for class ContentItem: template_type.");

            return new ContentItem(type.Value!, value.Value!, templateType);
        }

        /// <summary>
        /// Serializes a <see cref="ContentItem" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="contentItem"></param>
        /// <param name="jsonSerializerOptions"></param>
        public override void Write(Utf8JsonWriter writer, ContentItem contentItem, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, contentItem, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ContentItem" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="contentItem"></param>
        /// <param name="jsonSerializerOptions"></param>
        public void WriteProperties(Utf8JsonWriter writer, ContentItem contentItem, JsonSerializerOptions jsonSerializerOptions)
        {
            if (contentItem.TemplateTypeOption.IsSet && contentItem.TemplateType == null)
                throw new JsonException("Cannot write null property ContentItem.TemplateType to non-nullable JSON property 'template_type'.");

            writer.WriteString("type", contentItem.Type);

            writer.WriteString("value", contentItem.Value);

            if (contentItem.TemplateTypeOption.IsSet)
            {
                var templateTypeRawValue = ContentItem.TemplateTypeEnumToJsonValue(contentItem.TemplateType);
                writer.WriteString("template_type", templateTypeRawValue);
            }
        }
    }
}
