// <auto-generated>
/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MailChannels.EmailApi.Client;

namespace MailChannels.EmailApi.Model
{
    /// <summary>
    /// CustomTrackingDomainListResponse
    /// </summary>
    public partial class CustomTrackingDomainListResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CustomTrackingDomainListResponse" /> class.
        /// </summary>
        /// <param name="customTrackingDomains">List of custom tracking domains matching the filter criteria</param>
        /// <param name="total">Total number of custom tracking domains</param>
        [JsonConstructor]
        public CustomTrackingDomainListResponse(List<CustomTrackingDomain> customTrackingDomains, int total)
        {
            CustomTrackingDomains = customTrackingDomains;
            Total = total;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// List of custom tracking domains matching the filter criteria
        /// </summary>
        /// <value>List of custom tracking domains matching the filter criteria</value>
        [JsonPropertyName("custom_tracking_domains")]
        public List<CustomTrackingDomain> CustomTrackingDomains { get; set; }

        /// <summary>
        /// Total number of custom tracking domains
        /// </summary>
        /// <value>Total number of custom tracking domains</value>
        [JsonPropertyName("total")]
        public int Total { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            return "CustomTrackingDomainListResponse { [REDACTED] }";
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CustomTrackingDomainListResponse" />
    /// </summary>
    public partial class CustomTrackingDomainListResponseJsonConverter : JsonConverter<CustomTrackingDomainListResponse>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="CustomTrackingDomainListResponseJsonConverter" /> class.
        /// </summary>
        public CustomTrackingDomainListResponseJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="CustomTrackingDomainListResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CustomTrackingDomainListResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<CustomTrackingDomain>?> customTrackingDomains = default;
            Option<int?> total = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "custom_tracking_domains":
                            customTrackingDomains = new Option<List<CustomTrackingDomain>?>(JsonSerializer.Deserialize<List<CustomTrackingDomain>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "total":
                            total = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!customTrackingDomains.IsSet)
                throw new JsonException("Property is required for class CustomTrackingDomainListResponse: custom_tracking_domains.");

            if (!total.IsSet)
                throw new JsonException("Property is required for class CustomTrackingDomainListResponse: total.");

            if (customTrackingDomains.IsSet && customTrackingDomains.Value == null)
                throw new JsonException("Property is not nullable for class CustomTrackingDomainListResponse: custom_tracking_domains.");

            if (total.IsSet && total.Value == null)
                throw new JsonException("Property is not nullable for class CustomTrackingDomainListResponse: total.");

            return new CustomTrackingDomainListResponse(customTrackingDomains.Value!, total.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="CustomTrackingDomainListResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="customTrackingDomainListResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        public override void Write(Utf8JsonWriter writer, CustomTrackingDomainListResponse customTrackingDomainListResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, customTrackingDomainListResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CustomTrackingDomainListResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="customTrackingDomainListResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        public void WriteProperties(Utf8JsonWriter writer, CustomTrackingDomainListResponse customTrackingDomainListResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WritePropertyName("custom_tracking_domains");
            JsonSerializer.Serialize(writer, customTrackingDomainListResponse.CustomTrackingDomains, jsonSerializerOptions);
            writer.WriteNumber("total", customTrackingDomainListResponse.Total);
        }
    }
}
