// <auto-generated>
/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MailChannels.EmailApi.Client;

namespace MailChannels.EmailApi.Model
{
    /// <summary>
    /// CustomTrackingDomain
    /// </summary>
    public partial class CustomTrackingDomain : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CustomTrackingDomain" /> class.
        /// </summary>
        /// <param name="createdAt">ISO 8601 timestamp when the domain was registered</param>
        /// <param name="hostname">The registered domain hostname</param>
        /// <param name="name">The label for this custom tracking domain</param>
        /// <param name="scope">The event type this domain handles</param>
        /// <param name="status">Current status of the custom tracking domain</param>
        [JsonConstructor]
        public CustomTrackingDomain(DateTime createdAt, string hostname, string name, ScopeEnum scope, StatusEnum status)
        {
            CreatedAt = createdAt;
            Hostname = hostname;
            Name = name;
            Scope = scope;
            Status = status;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The event type this domain handles
        /// </summary>
        /// <value>The event type this domain handles</value>
        public enum ScopeEnum
        {
            /// <summary>
            /// Enum Click for value: click
            /// </summary>
            Click = 1,

            /// <summary>
            /// Enum Open for value: open
            /// </summary>
            Open = 2,

            /// <summary>
            /// Enum Unsubscribe for value: unsubscribe
            /// </summary>
            Unsubscribe = 3
        }

        /// <summary>
        /// Returns a <see cref="ScopeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static ScopeEnum ScopeEnumFromString(string value)
        {
            if (value.Equals("click"))
                return ScopeEnum.Click;

            if (value.Equals("open"))
                return ScopeEnum.Open;

            if (value.Equals("unsubscribe"))
                return ScopeEnum.Unsubscribe;

            throw new NotImplementedException($"Could not convert value to type ScopeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="ScopeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ScopeEnum? ScopeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("click"))
                return ScopeEnum.Click;

            if (value.Equals("open"))
                return ScopeEnum.Open;

            if (value.Equals("unsubscribe"))
                return ScopeEnum.Unsubscribe;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="ScopeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ScopeEnumToJsonValue(ScopeEnum value)
        {
            if (value == ScopeEnum.Click)
                return "click";

            if (value == ScopeEnum.Open)
                return "open";

            if (value == ScopeEnum.Unsubscribe)
                return "unsubscribe";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// The event type this domain handles
        /// </summary>
        /// <value>The event type this domain handles</value>
        [JsonPropertyName("scope")]
        public ScopeEnum Scope { get; set; }

        /// <summary>
        /// Current status of the custom tracking domain
        /// </summary>
        /// <value>Current status of the custom tracking domain</value>
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Active for value: active
            /// </summary>
            Active = 1,

            /// <summary>
            /// Enum Disabled for value: disabled
            /// </summary>
            Disabled = 2
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static StatusEnum StatusEnumFromString(string value)
        {
            if (value.Equals("active"))
                return StatusEnum.Active;

            if (value.Equals("disabled"))
                return StatusEnum.Disabled;

            throw new NotImplementedException($"Could not convert value to type StatusEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static StatusEnum? StatusEnumFromStringOrDefault(string value)
        {
            if (value.Equals("active"))
                return StatusEnum.Active;

            if (value.Equals("disabled"))
                return StatusEnum.Disabled;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="StatusEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string StatusEnumToJsonValue(StatusEnum value)
        {
            if (value == StatusEnum.Active)
                return "active";

            if (value == StatusEnum.Disabled)
                return "disabled";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Current status of the custom tracking domain
        /// </summary>
        /// <value>Current status of the custom tracking domain</value>
        [JsonPropertyName("status")]
        public StatusEnum Status { get; set; }

        /// <summary>
        /// ISO 8601 timestamp when the domain was registered
        /// </summary>
        /// <value>ISO 8601 timestamp when the domain was registered</value>
        [JsonPropertyName("created_at")]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// The registered domain hostname
        /// </summary>
        /// <value>The registered domain hostname</value>
        [JsonPropertyName("hostname")]
        public string Hostname { get; set; }

        /// <summary>
        /// The label for this custom tracking domain
        /// </summary>
        /// <value>The label for this custom tracking domain</value>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            return "CustomTrackingDomain { [REDACTED] }";
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CustomTrackingDomain" />
    /// </summary>
    public partial class CustomTrackingDomainJsonConverter : JsonConverter<CustomTrackingDomain>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="CustomTrackingDomainJsonConverter" /> class.
        /// </summary>
        public CustomTrackingDomainJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize CreatedAt
        /// </summary>
        public string CreatedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="CustomTrackingDomain" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CustomTrackingDomain Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<DateTime?> createdAt = default;
            Option<string?> hostname = default;
            Option<string?> name = default;
            Option<CustomTrackingDomain.ScopeEnum?> scope = default;
            Option<CustomTrackingDomain.StatusEnum?> status = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "created_at":
                            createdAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "hostname":
                            hostname = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "scope":
                            string? scopeRawValue = utf8JsonReader.GetString();
                            if (scopeRawValue != null)
                            {
                                CustomTrackingDomain.ScopeEnum? scopeValue = CustomTrackingDomain.ScopeEnumFromStringOrDefault(scopeRawValue);
                                if (scopeValue == null)
                                    throw new JsonException();
                                scope = new Option<CustomTrackingDomain.ScopeEnum?>(scopeValue);
                            }
                            break;
                        case "status":
                            string? statusRawValue = utf8JsonReader.GetString();
                            if (statusRawValue != null)
                            {
                                CustomTrackingDomain.StatusEnum? statusValue = CustomTrackingDomain.StatusEnumFromStringOrDefault(statusRawValue);
                                if (statusValue == null)
                                    throw new JsonException();
                                status = new Option<CustomTrackingDomain.StatusEnum?>(statusValue);
                            }
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!createdAt.IsSet)
                throw new JsonException("Property is required for class CustomTrackingDomain: created_at.");

            if (!hostname.IsSet)
                throw new JsonException("Property is required for class CustomTrackingDomain: hostname.");

            if (!name.IsSet)
                throw new JsonException("Property is required for class CustomTrackingDomain: name.");

            if (!scope.IsSet)
                throw new JsonException("Property is required for class CustomTrackingDomain: scope.");

            if (!status.IsSet)
                throw new JsonException("Property is required for class CustomTrackingDomain: status.");

            if (createdAt.IsSet && createdAt.Value == null)
                throw new JsonException("Property is not nullable for class CustomTrackingDomain: created_at.");

            if (hostname.IsSet && hostname.Value == null)
                throw new JsonException("Property is not nullable for class CustomTrackingDomain: hostname.");

            if (name.IsSet && name.Value == null)
                throw new JsonException("Property is not nullable for class CustomTrackingDomain: name.");

            if (scope.IsSet && scope.Value == null)
                throw new JsonException("Property is not nullable for class CustomTrackingDomain: scope.");

            if (status.IsSet && status.Value == null)
                throw new JsonException("Property is not nullable for class CustomTrackingDomain: status.");

            return new CustomTrackingDomain(createdAt.Value!.Value!, hostname.Value!, name.Value!, scope.Value!.Value!, status.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="CustomTrackingDomain" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="customTrackingDomain"></param>
        /// <param name="jsonSerializerOptions"></param>
        public override void Write(Utf8JsonWriter writer, CustomTrackingDomain customTrackingDomain, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, customTrackingDomain, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CustomTrackingDomain" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="customTrackingDomain"></param>
        /// <param name="jsonSerializerOptions"></param>
        public void WriteProperties(Utf8JsonWriter writer, CustomTrackingDomain customTrackingDomain, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteString("created_at", customTrackingDomain.CreatedAt.ToString(CreatedAtFormat));

            writer.WriteString("hostname", customTrackingDomain.Hostname);

            writer.WriteString("name", customTrackingDomain.Name);

                var scopeRawValue = CustomTrackingDomain.ScopeEnumToJsonValue(customTrackingDomain.Scope);
                writer.WriteString("scope", scopeRawValue);
                var statusRawValue = CustomTrackingDomain.StatusEnumToJsonValue(customTrackingDomain.Status);
                writer.WriteString("status", statusRawValue);
        }
    }
}
