// <auto-generated>
/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MailChannels.EmailApi.Client;

namespace MailChannels.EmailApi.Model
{
    /// <summary>
    /// DkimResult
    /// </summary>
    public partial class DkimResult : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DkimResult" /> class.
        /// </summary>
        /// <param name="dkimDomain">dkimDomain</param>
        /// <param name="dkimKeyStatus">The human readable status of the DKIM key used for verification. This field is only present if the DKIM check was performed using a DKIM key managed by MailChannels. If a DKIM key is present in the request, this field will not be included. </param>
        /// <param name="dkimSelector">dkimSelector</param>
        /// <param name="reason">A human-readable explanation of DKIM check.</param>
        /// <param name="verdict">verdict</param>
        [JsonConstructor]
        public DkimResult(Option<string?> dkimDomain = default, Option<string?> dkimKeyStatus = default, Option<string?> dkimSelector = default, Option<string?> reason = default, Option<VerdictEnum?> verdict = default)
        {
            DkimDomainOption = dkimDomain;
            DkimKeyStatusOption = dkimKeyStatus;
            DkimSelectorOption = dkimSelector;
            ReasonOption = reason;
            VerdictOption = verdict;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Verdict
        /// </summary>
        public enum VerdictEnum
        {
            /// <summary>
            /// Enum Passed for value: passed
            /// </summary>
            Passed = 1,

            /// <summary>
            /// Enum Failed for value: failed
            /// </summary>
            Failed = 2
        }

        /// <summary>
        /// Returns a <see cref="VerdictEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static VerdictEnum VerdictEnumFromString(string value)
        {
            if (value.Equals("passed"))
                return VerdictEnum.Passed;

            if (value.Equals("failed"))
                return VerdictEnum.Failed;

            throw new NotImplementedException($"Could not convert value to type VerdictEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="VerdictEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static VerdictEnum? VerdictEnumFromStringOrDefault(string value)
        {
            if (value.Equals("passed"))
                return VerdictEnum.Passed;

            if (value.Equals("failed"))
                return VerdictEnum.Failed;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="VerdictEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string VerdictEnumToJsonValue(VerdictEnum? value)
        {
            if (value == VerdictEnum.Passed)
                return "passed";

            if (value == VerdictEnum.Failed)
                return "failed";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Verdict
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<VerdictEnum?> VerdictOption { get; private set; }

        /// <summary>
        /// Gets or Sets Verdict
        /// </summary>
        [JsonPropertyName("verdict")]
        public VerdictEnum? Verdict { get { return this.VerdictOption.Value; } set { this.VerdictOption = new(value); } }

        /// <summary>
        /// Used to track the state of DkimDomain
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DkimDomainOption { get; private set; }

        /// <summary>
        /// Gets or Sets DkimDomain
        /// </summary>
        [JsonPropertyName("dkim_domain")]
        public string? DkimDomain { get { return this.DkimDomainOption.Value; } set { this.DkimDomainOption = new(value); } }

        /// <summary>
        /// Used to track the state of DkimKeyStatus
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DkimKeyStatusOption { get; private set; }

        /// <summary>
        /// The human readable status of the DKIM key used for verification. This field is only present if the DKIM check was performed using a DKIM key managed by MailChannels. If a DKIM key is present in the request, this field will not be included. 
        /// </summary>
        /// <value>The human readable status of the DKIM key used for verification. This field is only present if the DKIM check was performed using a DKIM key managed by MailChannels. If a DKIM key is present in the request, this field will not be included. </value>
        [JsonPropertyName("dkim_key_status")]
        public string? DkimKeyStatus { get { return this.DkimKeyStatusOption.Value; } set { this.DkimKeyStatusOption = new(value); } }

        /// <summary>
        /// Used to track the state of DkimSelector
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DkimSelectorOption { get; private set; }

        /// <summary>
        /// Gets or Sets DkimSelector
        /// </summary>
        [JsonPropertyName("dkim_selector")]
        public string? DkimSelector { get { return this.DkimSelectorOption.Value; } set { this.DkimSelectorOption = new(value); } }

        /// <summary>
        /// Used to track the state of Reason
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ReasonOption { get; private set; }

        /// <summary>
        /// A human-readable explanation of DKIM check.
        /// </summary>
        /// <value>A human-readable explanation of DKIM check.</value>
        [JsonPropertyName("reason")]
        public string? Reason { get { return this.ReasonOption.Value; } set { this.ReasonOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            return "DkimResult { [REDACTED] }";
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="DkimResult" />
    /// </summary>
    public partial class DkimResultJsonConverter : JsonConverter<DkimResult>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="DkimResultJsonConverter" /> class.
        /// </summary>
        public DkimResultJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="DkimResult" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override DkimResult Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> dkimDomain = default;
            Option<string?> dkimKeyStatus = default;
            Option<string?> dkimSelector = default;
            Option<string?> reason = default;
            Option<DkimResult.VerdictEnum?> verdict = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "dkim_domain":
                            dkimDomain = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "dkim_key_status":
                            dkimKeyStatus = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "dkim_selector":
                            dkimSelector = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "reason":
                            reason = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "verdict":
                            string? verdictRawValue = utf8JsonReader.GetString();
                            if (verdictRawValue != null)
                            {
                                DkimResult.VerdictEnum? verdictValue = DkimResult.VerdictEnumFromStringOrDefault(verdictRawValue);
                                if (verdictValue == null)
                                    throw new JsonException();
                                verdict = new Option<DkimResult.VerdictEnum?>(verdictValue);
                            }
                            break;
                        default:
                            break;
                    }
                }
            }

            if (dkimDomain.IsSet && dkimDomain.Value == null)
                throw new JsonException("Property is not nullable for class DkimResult: dkim_domain.");

            if (dkimKeyStatus.IsSet && dkimKeyStatus.Value == null)
                throw new JsonException("Property is not nullable for class DkimResult: dkim_key_status.");

            if (dkimSelector.IsSet && dkimSelector.Value == null)
                throw new JsonException("Property is not nullable for class DkimResult: dkim_selector.");

            if (reason.IsSet && reason.Value == null)
                throw new JsonException("Property is not nullable for class DkimResult: reason.");

            if (verdict.IsSet && verdict.Value == null)
                throw new JsonException("Property is not nullable for class DkimResult: verdict.");

            return new DkimResult(dkimDomain, dkimKeyStatus, dkimSelector, reason, verdict);
        }

        /// <summary>
        /// Serializes a <see cref="DkimResult" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="dkimResult"></param>
        /// <param name="jsonSerializerOptions"></param>
        public override void Write(Utf8JsonWriter writer, DkimResult dkimResult, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, dkimResult, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="DkimResult" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="dkimResult"></param>
        /// <param name="jsonSerializerOptions"></param>
        public void WriteProperties(Utf8JsonWriter writer, DkimResult dkimResult, JsonSerializerOptions jsonSerializerOptions)
        {
            if (dkimResult.DkimDomainOption.IsSet && dkimResult.DkimDomain == null)
                throw new JsonException("Cannot write null property DkimResult.DkimDomain to non-nullable JSON property 'dkim_domain'.");

            if (dkimResult.DkimKeyStatusOption.IsSet && dkimResult.DkimKeyStatus == null)
                throw new JsonException("Cannot write null property DkimResult.DkimKeyStatus to non-nullable JSON property 'dkim_key_status'.");

            if (dkimResult.DkimSelectorOption.IsSet && dkimResult.DkimSelector == null)
                throw new JsonException("Cannot write null property DkimResult.DkimSelector to non-nullable JSON property 'dkim_selector'.");

            if (dkimResult.ReasonOption.IsSet && dkimResult.Reason == null)
                throw new JsonException("Cannot write null property DkimResult.Reason to non-nullable JSON property 'reason'.");

            if (dkimResult.VerdictOption.IsSet && dkimResult.Verdict == null)
                throw new JsonException("Cannot write null property DkimResult.Verdict to non-nullable JSON property 'verdict'.");

            if (dkimResult.DkimDomainOption.IsSet)
                writer.WriteString("dkim_domain", dkimResult.DkimDomain);

            if (dkimResult.DkimKeyStatusOption.IsSet)
                writer.WriteString("dkim_key_status", dkimResult.DkimKeyStatus);

            if (dkimResult.DkimSelectorOption.IsSet)
                writer.WriteString("dkim_selector", dkimResult.DkimSelector);

            if (dkimResult.ReasonOption.IsSet)
                writer.WriteString("reason", dkimResult.Reason);

            if (dkimResult.VerdictOption.IsSet)
            {
                var verdictRawValue = DkimResult.VerdictEnumToJsonValue(dkimResult.Verdict);
                writer.WriteString("verdict", verdictRawValue);
            }
        }
    }
}
