// <auto-generated>
/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MailChannels.EmailApi.Client;

namespace MailChannels.EmailApi.Model
{
    /// <summary>
    /// DKIMKeyPairUpdateRequest
    /// </summary>
    public partial class DKIMKeyPairUpdateRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DKIMKeyPairUpdateRequest" /> class.
        /// </summary>
        /// <param name="status">New status of the DKIM key pair </param>
        [JsonConstructor]
        public DKIMKeyPairUpdateRequest(StatusEnum status)
        {
            Status = status;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// New status of the DKIM key pair 
        /// </summary>
        /// <value>New status of the DKIM key pair </value>
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Revoked for value: revoked
            /// </summary>
            Revoked = 1,

            /// <summary>
            /// Enum Retired for value: retired
            /// </summary>
            Retired = 2,

            /// <summary>
            /// Enum Rotated for value: rotated
            /// </summary>
            Rotated = 3
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static StatusEnum StatusEnumFromString(string value)
        {
            if (value.Equals("revoked"))
                return StatusEnum.Revoked;

            if (value.Equals("retired"))
                return StatusEnum.Retired;

            if (value.Equals("rotated"))
                return StatusEnum.Rotated;

            throw new NotImplementedException($"Could not convert value to type StatusEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static StatusEnum? StatusEnumFromStringOrDefault(string value)
        {
            if (value.Equals("revoked"))
                return StatusEnum.Revoked;

            if (value.Equals("retired"))
                return StatusEnum.Retired;

            if (value.Equals("rotated"))
                return StatusEnum.Rotated;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="StatusEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string StatusEnumToJsonValue(StatusEnum value)
        {
            if (value == StatusEnum.Revoked)
                return "revoked";

            if (value == StatusEnum.Retired)
                return "retired";

            if (value == StatusEnum.Rotated)
                return "rotated";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// New status of the DKIM key pair 
        /// </summary>
        /// <value>New status of the DKIM key pair </value>
        [JsonPropertyName("status")]
        public StatusEnum Status { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            return "DKIMKeyPairUpdateRequest { [REDACTED] }";
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="DKIMKeyPairUpdateRequest" />
    /// </summary>
    public partial class DKIMKeyPairUpdateRequestJsonConverter : JsonConverter<DKIMKeyPairUpdateRequest>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="DKIMKeyPairUpdateRequestJsonConverter" /> class.
        /// </summary>
        public DKIMKeyPairUpdateRequestJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="DKIMKeyPairUpdateRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override DKIMKeyPairUpdateRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<DKIMKeyPairUpdateRequest.StatusEnum?> status = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "status":
                            string? statusRawValue = utf8JsonReader.GetString();
                            if (statusRawValue != null)
                            {
                                DKIMKeyPairUpdateRequest.StatusEnum? statusValue = DKIMKeyPairUpdateRequest.StatusEnumFromStringOrDefault(statusRawValue);
                                if (statusValue == null)
                                    throw new JsonException();
                                status = new Option<DKIMKeyPairUpdateRequest.StatusEnum?>(statusValue);
                            }
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!status.IsSet)
                throw new JsonException("Property is required for class DKIMKeyPairUpdateRequest: status.");

            if (status.IsSet && status.Value == null)
                throw new JsonException("Property is not nullable for class DKIMKeyPairUpdateRequest: status.");

            return new DKIMKeyPairUpdateRequest(status.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="DKIMKeyPairUpdateRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="dKIMKeyPairUpdateRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        public override void Write(Utf8JsonWriter writer, DKIMKeyPairUpdateRequest dKIMKeyPairUpdateRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, dKIMKeyPairUpdateRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="DKIMKeyPairUpdateRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="dKIMKeyPairUpdateRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        public void WriteProperties(Utf8JsonWriter writer, DKIMKeyPairUpdateRequest dKIMKeyPairUpdateRequest, JsonSerializerOptions jsonSerializerOptions)
        {
                var statusRawValue = DKIMKeyPairUpdateRequest.StatusEnumToJsonValue(dKIMKeyPairUpdateRequest.Status);
                writer.WriteString("status", statusRawValue);
        }
    }
}
