// <auto-generated>
/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MailChannels.EmailApi.Client;

namespace MailChannels.EmailApi.Model
{
    /// <summary>
    /// DKIMKeyRotateRequest
    /// </summary>
    public partial class DKIMKeyRotateRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DKIMKeyRotateRequest" /> class.
        /// </summary>
        /// <param name="newKey">newKey</param>
        [JsonConstructor]
        public DKIMKeyRotateRequest(NewKey newKey)
        {
            NewKey = newKey;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets NewKey
        /// </summary>
        [JsonPropertyName("new_key")]
        public NewKey NewKey { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            return "DKIMKeyRotateRequest { [REDACTED] }";
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="DKIMKeyRotateRequest" />
    /// </summary>
    public partial class DKIMKeyRotateRequestJsonConverter : JsonConverter<DKIMKeyRotateRequest>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="DKIMKeyRotateRequestJsonConverter" /> class.
        /// </summary>
        public DKIMKeyRotateRequestJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="DKIMKeyRotateRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override DKIMKeyRotateRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<NewKey?> newKey = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "new_key":
                            newKey = new Option<NewKey?>(JsonSerializer.Deserialize<NewKey>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!newKey.IsSet)
                throw new JsonException("Property is required for class DKIMKeyRotateRequest: new_key.");

            if (newKey.IsSet && newKey.Value == null)
                throw new JsonException("Property is not nullable for class DKIMKeyRotateRequest: new_key.");

            return new DKIMKeyRotateRequest(newKey.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="DKIMKeyRotateRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="dKIMKeyRotateRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        public override void Write(Utf8JsonWriter writer, DKIMKeyRotateRequest dKIMKeyRotateRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, dKIMKeyRotateRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="DKIMKeyRotateRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="dKIMKeyRotateRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        public void WriteProperties(Utf8JsonWriter writer, DKIMKeyRotateRequest dKIMKeyRotateRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WritePropertyName("new_key");
            JsonSerializer.Serialize(writer, dKIMKeyRotateRequest.NewKey, jsonSerializerOptions);
        }
    }
}
