// <auto-generated>
/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MailChannels.EmailApi.Client;

namespace MailChannels.EmailApi.Model
{
    /// <summary>
    /// DKIMKeyInfo
    /// </summary>
    public partial class DKIMKeyInfo : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DKIMKeyInfo" /> class.
        /// </summary>
        /// <param name="algorithm">Algorithm used for the key pair </param>
        /// <param name="domain">Domain associated with the key pair </param>
        /// <param name="publicKey">publicKey</param>
        /// <param name="selector">Selector assigned to the key pair </param>
        /// <param name="status">status</param>
        /// <param name="createdAt">Timestamp when the key pair was created </param>
        /// <param name="dkimDnsRecords">Suggested DNS records for the DKIM key </param>
        /// <param name="gracePeriodExpiresAt">UTC timestamp after which you can no longer use the rotated key for signing </param>
        /// <param name="keyLength">Key length in bits </param>
        /// <param name="retiresAt">UTC timestamp when a rotated key pair is retired </param>
        /// <param name="statusModifiedAt">Timestamp when the key was last modified </param>
        [JsonConstructor]
        public DKIMKeyInfo(string algorithm, string domain, string publicKey, string selector, StatusEnum status, Option<DateTime?> createdAt = default, Option<List<DKIMDnsRecord>?> dkimDnsRecords = default, Option<DateTime?> gracePeriodExpiresAt = default, Option<int?> keyLength = default, Option<DateTime?> retiresAt = default, Option<DateTime?> statusModifiedAt = default)
        {
            Algorithm = algorithm;
            Domain = domain;
            PublicKey = publicKey;
            Selector = selector;
            Status = status;
            CreatedAtOption = createdAt;
            DkimDnsRecordsOption = dkimDnsRecords;
            GracePeriodExpiresAtOption = gracePeriodExpiresAt;
            KeyLengthOption = keyLength;
            RetiresAtOption = retiresAt;
            StatusModifiedAtOption = statusModifiedAt;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Status
        /// </summary>
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Active for value: active
            /// </summary>
            Active = 1,

            /// <summary>
            /// Enum Retired for value: retired
            /// </summary>
            Retired = 2,

            /// <summary>
            /// Enum Revoked for value: revoked
            /// </summary>
            Revoked = 3,

            /// <summary>
            /// Enum Rotated for value: rotated
            /// </summary>
            Rotated = 4
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static StatusEnum StatusEnumFromString(string value)
        {
            if (value.Equals("active"))
                return StatusEnum.Active;

            if (value.Equals("retired"))
                return StatusEnum.Retired;

            if (value.Equals("revoked"))
                return StatusEnum.Revoked;

            if (value.Equals("rotated"))
                return StatusEnum.Rotated;

            throw new NotImplementedException($"Could not convert value to type StatusEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static StatusEnum? StatusEnumFromStringOrDefault(string value)
        {
            if (value.Equals("active"))
                return StatusEnum.Active;

            if (value.Equals("retired"))
                return StatusEnum.Retired;

            if (value.Equals("revoked"))
                return StatusEnum.Revoked;

            if (value.Equals("rotated"))
                return StatusEnum.Rotated;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="StatusEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string StatusEnumToJsonValue(StatusEnum value)
        {
            if (value == StatusEnum.Active)
                return "active";

            if (value == StatusEnum.Retired)
                return "retired";

            if (value == StatusEnum.Revoked)
                return "revoked";

            if (value == StatusEnum.Rotated)
                return "rotated";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public StatusEnum Status { get; set; }

        /// <summary>
        /// Algorithm used for the key pair 
        /// </summary>
        /// <value>Algorithm used for the key pair </value>
        [JsonPropertyName("algorithm")]
        public string Algorithm { get; set; }

        /// <summary>
        /// Domain associated with the key pair 
        /// </summary>
        /// <value>Domain associated with the key pair </value>
        [JsonPropertyName("domain")]
        public string Domain { get; set; }

        /// <summary>
        /// Gets or Sets PublicKey
        /// </summary>
        [JsonPropertyName("public_key")]
        public string PublicKey { get; set; }

        /// <summary>
        /// Selector assigned to the key pair 
        /// </summary>
        /// <value>Selector assigned to the key pair </value>
        [JsonPropertyName("selector")]
        public string Selector { get; set; }

        /// <summary>
        /// Used to track the state of CreatedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> CreatedAtOption { get; private set; }

        /// <summary>
        /// Timestamp when the key pair was created 
        /// </summary>
        /// <value>Timestamp when the key pair was created </value>
        [JsonPropertyName("created_at")]
        public DateTime? CreatedAt { get { return this.CreatedAtOption.Value; } set { this.CreatedAtOption = new(value); } }

        /// <summary>
        /// Used to track the state of DkimDnsRecords
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<DKIMDnsRecord>?> DkimDnsRecordsOption { get; private set; }

        /// <summary>
        /// Suggested DNS records for the DKIM key 
        /// </summary>
        /// <value>Suggested DNS records for the DKIM key </value>
        [JsonPropertyName("dkim_dns_records")]
        public List<DKIMDnsRecord>? DkimDnsRecords { get { return this.DkimDnsRecordsOption.Value; } set { this.DkimDnsRecordsOption = new(value); } }

        /// <summary>
        /// Used to track the state of GracePeriodExpiresAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> GracePeriodExpiresAtOption { get; private set; }

        /// <summary>
        /// UTC timestamp after which you can no longer use the rotated key for signing 
        /// </summary>
        /// <value>UTC timestamp after which you can no longer use the rotated key for signing </value>
        [JsonPropertyName("gracePeriodExpiresAt")]
        public DateTime? GracePeriodExpiresAt { get { return this.GracePeriodExpiresAtOption.Value; } set { this.GracePeriodExpiresAtOption = new(value); } }

        /// <summary>
        /// Used to track the state of KeyLength
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> KeyLengthOption { get; private set; }

        /// <summary>
        /// Key length in bits 
        /// </summary>
        /// <value>Key length in bits </value>
        [JsonPropertyName("key_length")]
        public int? KeyLength { get { return this.KeyLengthOption.Value; } set { this.KeyLengthOption = new(value); } }

        /// <summary>
        /// Used to track the state of RetiresAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> RetiresAtOption { get; private set; }

        /// <summary>
        /// UTC timestamp when a rotated key pair is retired 
        /// </summary>
        /// <value>UTC timestamp when a rotated key pair is retired </value>
        [JsonPropertyName("retiresAt")]
        public DateTime? RetiresAt { get { return this.RetiresAtOption.Value; } set { this.RetiresAtOption = new(value); } }

        /// <summary>
        /// Used to track the state of StatusModifiedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> StatusModifiedAtOption { get; private set; }

        /// <summary>
        /// Timestamp when the key was last modified 
        /// </summary>
        /// <value>Timestamp when the key was last modified </value>
        [JsonPropertyName("status_modified_at")]
        public DateTime? StatusModifiedAt { get { return this.StatusModifiedAtOption.Value; } set { this.StatusModifiedAtOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            return "DKIMKeyInfo { [REDACTED] }";
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="DKIMKeyInfo" />
    /// </summary>
    public partial class DKIMKeyInfoJsonConverter : JsonConverter<DKIMKeyInfo>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="DKIMKeyInfoJsonConverter" /> class.
        /// </summary>
        public DKIMKeyInfoJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize CreatedAt
        /// </summary>
        public string CreatedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize GracePeriodExpiresAt
        /// </summary>
        public string GracePeriodExpiresAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize RetiresAt
        /// </summary>
        public string RetiresAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize StatusModifiedAt
        /// </summary>
        public string StatusModifiedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="DKIMKeyInfo" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override DKIMKeyInfo Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> algorithm = default;
            Option<string?> domain = default;
            Option<string?> publicKey = default;
            Option<string?> selector = default;
            Option<DKIMKeyInfo.StatusEnum?> status = default;
            Option<DateTime?> createdAt = default;
            Option<List<DKIMDnsRecord>?> dkimDnsRecords = default;
            Option<DateTime?> gracePeriodExpiresAt = default;
            Option<int?> keyLength = default;
            Option<DateTime?> retiresAt = default;
            Option<DateTime?> statusModifiedAt = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "algorithm":
                            algorithm = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "domain":
                            domain = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "public_key":
                            publicKey = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "selector":
                            selector = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "status":
                            string? statusRawValue = utf8JsonReader.GetString();
                            if (statusRawValue != null)
                            {
                                DKIMKeyInfo.StatusEnum? statusValue = DKIMKeyInfo.StatusEnumFromStringOrDefault(statusRawValue);
                                if (statusValue == null)
                                    throw new JsonException();
                                status = new Option<DKIMKeyInfo.StatusEnum?>(statusValue);
                            }
                            break;
                        case "created_at":
                            createdAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "dkim_dns_records":
                            dkimDnsRecords = new Option<List<DKIMDnsRecord>?>(JsonSerializer.Deserialize<List<DKIMDnsRecord>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "gracePeriodExpiresAt":
                            gracePeriodExpiresAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "key_length":
                            keyLength = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "retiresAt":
                            retiresAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "status_modified_at":
                            statusModifiedAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!algorithm.IsSet)
                throw new JsonException("Property is required for class DKIMKeyInfo: algorithm.");

            if (!domain.IsSet)
                throw new JsonException("Property is required for class DKIMKeyInfo: domain.");

            if (!publicKey.IsSet)
                throw new JsonException("Property is required for class DKIMKeyInfo: public_key.");

            if (!selector.IsSet)
                throw new JsonException("Property is required for class DKIMKeyInfo: selector.");

            if (!status.IsSet)
                throw new JsonException("Property is required for class DKIMKeyInfo: status.");

            if (algorithm.IsSet && algorithm.Value == null)
                throw new JsonException("Property is not nullable for class DKIMKeyInfo: algorithm.");

            if (domain.IsSet && domain.Value == null)
                throw new JsonException("Property is not nullable for class DKIMKeyInfo: domain.");

            if (publicKey.IsSet && publicKey.Value == null)
                throw new JsonException("Property is not nullable for class DKIMKeyInfo: public_key.");

            if (selector.IsSet && selector.Value == null)
                throw new JsonException("Property is not nullable for class DKIMKeyInfo: selector.");

            if (status.IsSet && status.Value == null)
                throw new JsonException("Property is not nullable for class DKIMKeyInfo: status.");

            if (dkimDnsRecords.IsSet && dkimDnsRecords.Value == null)
                throw new JsonException("Property is not nullable for class DKIMKeyInfo: dkim_dns_records.");

            if (keyLength.IsSet && keyLength.Value == null)
                throw new JsonException("Property is not nullable for class DKIMKeyInfo: key_length.");

            return new DKIMKeyInfo(algorithm.Value!, domain.Value!, publicKey.Value!, selector.Value!, status.Value!.Value!, createdAt, dkimDnsRecords, gracePeriodExpiresAt, keyLength, retiresAt, statusModifiedAt);
        }

        /// <summary>
        /// Serializes a <see cref="DKIMKeyInfo" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="dKIMKeyInfo"></param>
        /// <param name="jsonSerializerOptions"></param>
        public override void Write(Utf8JsonWriter writer, DKIMKeyInfo dKIMKeyInfo, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, dKIMKeyInfo, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="DKIMKeyInfo" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="dKIMKeyInfo"></param>
        /// <param name="jsonSerializerOptions"></param>
        public void WriteProperties(Utf8JsonWriter writer, DKIMKeyInfo dKIMKeyInfo, JsonSerializerOptions jsonSerializerOptions)
        {
            if (dKIMKeyInfo.DkimDnsRecordsOption.IsSet && dKIMKeyInfo.DkimDnsRecords == null)
                throw new JsonException("Cannot write null property DKIMKeyInfo.DkimDnsRecords to non-nullable JSON property 'dkim_dns_records'.");

            if (dKIMKeyInfo.KeyLengthOption.IsSet && dKIMKeyInfo.KeyLength == null)
                throw new JsonException("Cannot write null property DKIMKeyInfo.KeyLength to non-nullable JSON property 'key_length'.");

            writer.WriteString("algorithm", dKIMKeyInfo.Algorithm);

            writer.WriteString("domain", dKIMKeyInfo.Domain);

            writer.WriteString("public_key", dKIMKeyInfo.PublicKey);

            writer.WriteString("selector", dKIMKeyInfo.Selector);

                var statusRawValue = DKIMKeyInfo.StatusEnumToJsonValue(dKIMKeyInfo.Status);
                writer.WriteString("status", statusRawValue);
            if (dKIMKeyInfo.CreatedAtOption.IsSet)
                if (dKIMKeyInfo.CreatedAtOption.Value != null)
                    writer.WriteString("created_at", dKIMKeyInfo.CreatedAtOption.Value!.Value.ToString(CreatedAtFormat));
                else
                    writer.WriteNull("created_at");

            if (dKIMKeyInfo.DkimDnsRecordsOption.IsSet)
            {
                writer.WritePropertyName("dkim_dns_records");
                JsonSerializer.Serialize(writer, dKIMKeyInfo.DkimDnsRecords, jsonSerializerOptions);
            }
            if (dKIMKeyInfo.GracePeriodExpiresAtOption.IsSet)
                if (dKIMKeyInfo.GracePeriodExpiresAtOption.Value != null)
                    writer.WriteString("gracePeriodExpiresAt", dKIMKeyInfo.GracePeriodExpiresAtOption.Value!.Value.ToString(GracePeriodExpiresAtFormat));
                else
                    writer.WriteNull("gracePeriodExpiresAt");

            if (dKIMKeyInfo.KeyLengthOption.IsSet)
                writer.WriteNumber("key_length", dKIMKeyInfo.KeyLengthOption.Value!.Value);

            if (dKIMKeyInfo.RetiresAtOption.IsSet)
                if (dKIMKeyInfo.RetiresAtOption.Value != null)
                    writer.WriteString("retiresAt", dKIMKeyInfo.RetiresAtOption.Value!.Value.ToString(RetiresAtFormat));
                else
                    writer.WriteNull("retiresAt");

            if (dKIMKeyInfo.StatusModifiedAtOption.IsSet)
                if (dKIMKeyInfo.StatusModifiedAtOption.Value != null)
                    writer.WriteString("status_modified_at", dKIMKeyInfo.StatusModifiedAtOption.Value!.Value.ToString(StatusModifiedAtFormat));
                else
                    writer.WriteNull("status_modified_at");
        }
    }
}
