// <auto-generated>
/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MailChannels.EmailApi.Client;

namespace MailChannels.EmailApi.Model
{
    /// <summary>
    /// DKIMKeyList
    /// </summary>
    public partial class DKIMKeyList : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DKIMKeyList" /> class.
        /// </summary>
        /// <param name="keys">List of keys matching the filter. Empty if no keys match the filter. </param>
        [JsonConstructor]
        public DKIMKeyList(List<DKIMKeyInfo> keys)
        {
            Keys = keys;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// List of keys matching the filter. Empty if no keys match the filter. 
        /// </summary>
        /// <value>List of keys matching the filter. Empty if no keys match the filter. </value>
        [JsonPropertyName("keys")]
        public List<DKIMKeyInfo> Keys { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            return "DKIMKeyList { [REDACTED] }";
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="DKIMKeyList" />
    /// </summary>
    public partial class DKIMKeyListJsonConverter : JsonConverter<DKIMKeyList>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="DKIMKeyListJsonConverter" /> class.
        /// </summary>
        public DKIMKeyListJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="DKIMKeyList" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override DKIMKeyList Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<DKIMKeyInfo>?> keys = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "keys":
                            keys = new Option<List<DKIMKeyInfo>?>(JsonSerializer.Deserialize<List<DKIMKeyInfo>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!keys.IsSet)
                throw new JsonException("Property is required for class DKIMKeyList: keys.");

            if (keys.IsSet && keys.Value == null)
                throw new JsonException("Property is not nullable for class DKIMKeyList: keys.");

            return new DKIMKeyList(keys.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="DKIMKeyList" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="dKIMKeyList"></param>
        /// <param name="jsonSerializerOptions"></param>
        public override void Write(Utf8JsonWriter writer, DKIMKeyList dKIMKeyList, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, dKIMKeyList, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="DKIMKeyList" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="dKIMKeyList"></param>
        /// <param name="jsonSerializerOptions"></param>
        public void WriteProperties(Utf8JsonWriter writer, DKIMKeyList dKIMKeyList, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WritePropertyName("keys");
            JsonSerializer.Serialize(writer, dKIMKeyList.Keys, jsonSerializerOptions);
        }
    }
}
