// <auto-generated>
/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MailChannels.EmailApi.Client;

namespace MailChannels.EmailApi.Model
{
    /// <summary>
    /// EmailAddress
    /// </summary>
    public partial class EmailAddress : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EmailAddress" /> class.
        /// </summary>
        /// <param name="email">email</param>
        /// <param name="name">Display name in raw text, e.g. John Doe, 张三</param>
        [JsonConstructor]
        public EmailAddress(string email, Option<string?> name = default)
        {
            Email = email;
            NameOption = name;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Email
        /// </summary>
        [JsonPropertyName("email")]
        public string Email { get; set; }

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// Display name in raw text, e.g. John Doe, 张三
        /// </summary>
        /// <value>Display name in raw text, e.g. John Doe, 张三</value>
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption.Value; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            return "EmailAddress { [REDACTED] }";
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EmailAddress" />
    /// </summary>
    public partial class EmailAddressJsonConverter : JsonConverter<EmailAddress>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="EmailAddressJsonConverter" /> class.
        /// </summary>
        public EmailAddressJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="EmailAddress" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EmailAddress Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> email = default;
            Option<string?> name = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "email":
                            email = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!email.IsSet)
                throw new JsonException("Property is required for class EmailAddress: email.");

            if (email.IsSet && email.Value == null)
                throw new JsonException("Property is not nullable for class EmailAddress: email.");

            if (name.IsSet && name.Value == null)
                throw new JsonException("Property is not nullable for class EmailAddress: name.");

            return new EmailAddress(email.Value!, name);
        }

        /// <summary>
        /// Serializes a <see cref="EmailAddress" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="emailAddress"></param>
        /// <param name="jsonSerializerOptions"></param>
        public override void Write(Utf8JsonWriter writer, EmailAddress emailAddress, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, emailAddress, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="EmailAddress" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="emailAddress"></param>
        /// <param name="jsonSerializerOptions"></param>
        public void WriteProperties(Utf8JsonWriter writer, EmailAddress emailAddress, JsonSerializerOptions jsonSerializerOptions)
        {
            if (emailAddress.NameOption.IsSet && emailAddress.Name == null)
                throw new JsonException("Cannot write null property EmailAddress.Name to non-nullable JSON property 'name'.");

            writer.WriteString("email", emailAddress.Email);

            if (emailAddress.NameOption.IsSet)
                writer.WriteString("name", emailAddress.Name);
        }
    }
}
