// <auto-generated>
/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MailChannels.EmailApi.Client;

namespace MailChannels.EmailApi.Model
{
    /// <summary>
    /// LimitUpdateResult
    /// </summary>
    public partial class LimitUpdateResult : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LimitUpdateResult" /> class.
        /// </summary>
        /// <param name="limit">limit</param>
        [JsonConstructor]
        public LimitUpdateResult(Option<Limit?> limit = default)
        {
            LimitOption = limit;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Limit
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Limit?> LimitOption { get; private set; }

        /// <summary>
        /// Gets or Sets Limit
        /// </summary>
        [JsonPropertyName("limit")]
        public Limit? Limit { get { return this.LimitOption.Value; } set { this.LimitOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            return "LimitUpdateResult { [REDACTED] }";
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="LimitUpdateResult" />
    /// </summary>
    public partial class LimitUpdateResultJsonConverter : JsonConverter<LimitUpdateResult>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="LimitUpdateResultJsonConverter" /> class.
        /// </summary>
        public LimitUpdateResultJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="LimitUpdateResult" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override LimitUpdateResult Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Limit?> limit = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "limit":
                            limit = new Option<Limit?>(JsonSerializer.Deserialize<Limit>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (limit.IsSet && limit.Value == null)
                throw new JsonException("Property is not nullable for class LimitUpdateResult: limit.");

            return new LimitUpdateResult(limit);
        }

        /// <summary>
        /// Serializes a <see cref="LimitUpdateResult" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="limitUpdateResult"></param>
        /// <param name="jsonSerializerOptions"></param>
        public override void Write(Utf8JsonWriter writer, LimitUpdateResult limitUpdateResult, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, limitUpdateResult, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="LimitUpdateResult" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="limitUpdateResult"></param>
        /// <param name="jsonSerializerOptions"></param>
        public void WriteProperties(Utf8JsonWriter writer, LimitUpdateResult limitUpdateResult, JsonSerializerOptions jsonSerializerOptions)
        {
            if (limitUpdateResult.LimitOption.IsSet && limitUpdateResult.Limit == null)
                throw new JsonException("Cannot write null property LimitUpdateResult.Limit to non-nullable JSON property 'limit'.");

            if (limitUpdateResult.LimitOption.IsSet)
            {
                writer.WritePropertyName("limit");
                JsonSerializer.Serialize(writer, limitUpdateResult.Limit, jsonSerializerOptions);
            }
        }
    }
}
