// <auto-generated>
/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MailChannels.EmailApi.Client;

namespace MailChannels.EmailApi.Model
{
    /// <summary>
    /// LockdownResult
    /// </summary>
    public partial class LockdownResult : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LockdownResult" /> class.
        /// </summary>
        /// <param name="reason">A human-readable explanation of Domain Lockdown check. </param>
        /// <param name="verdict">verdict</param>
        [JsonConstructor]
        public LockdownResult(Option<string?> reason = default, Option<VerdictEnum?> verdict = default)
        {
            ReasonOption = reason;
            VerdictOption = verdict;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Verdict
        /// </summary>
        public enum VerdictEnum
        {
            /// <summary>
            /// Enum Passed for value: passed
            /// </summary>
            Passed = 1,

            /// <summary>
            /// Enum Failed for value: failed
            /// </summary>
            Failed = 2
        }

        /// <summary>
        /// Returns a <see cref="VerdictEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static VerdictEnum VerdictEnumFromString(string value)
        {
            if (value.Equals("passed"))
                return VerdictEnum.Passed;

            if (value.Equals("failed"))
                return VerdictEnum.Failed;

            throw new NotImplementedException($"Could not convert value to type VerdictEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="VerdictEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static VerdictEnum? VerdictEnumFromStringOrDefault(string value)
        {
            if (value.Equals("passed"))
                return VerdictEnum.Passed;

            if (value.Equals("failed"))
                return VerdictEnum.Failed;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="VerdictEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string VerdictEnumToJsonValue(VerdictEnum? value)
        {
            if (value == VerdictEnum.Passed)
                return "passed";

            if (value == VerdictEnum.Failed)
                return "failed";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Verdict
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<VerdictEnum?> VerdictOption { get; private set; }

        /// <summary>
        /// Gets or Sets Verdict
        /// </summary>
        [JsonPropertyName("verdict")]
        public VerdictEnum? Verdict { get { return this.VerdictOption.Value; } set { this.VerdictOption = new(value); } }

        /// <summary>
        /// Used to track the state of Reason
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ReasonOption { get; private set; }

        /// <summary>
        /// A human-readable explanation of Domain Lockdown check. 
        /// </summary>
        /// <value>A human-readable explanation of Domain Lockdown check. </value>
        [JsonPropertyName("reason")]
        public string? Reason { get { return this.ReasonOption.Value; } set { this.ReasonOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            return "LockdownResult { [REDACTED] }";
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="LockdownResult" />
    /// </summary>
    public partial class LockdownResultJsonConverter : JsonConverter<LockdownResult>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="LockdownResultJsonConverter" /> class.
        /// </summary>
        public LockdownResultJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="LockdownResult" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override LockdownResult Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> reason = default;
            Option<LockdownResult.VerdictEnum?> verdict = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "reason":
                            reason = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "verdict":
                            string? verdictRawValue = utf8JsonReader.GetString();
                            if (verdictRawValue != null)
                            {
                                LockdownResult.VerdictEnum? verdictValue = LockdownResult.VerdictEnumFromStringOrDefault(verdictRawValue);
                                if (verdictValue == null)
                                    throw new JsonException();
                                verdict = new Option<LockdownResult.VerdictEnum?>(verdictValue);
                            }
                            break;
                        default:
                            break;
                    }
                }
            }

            if (reason.IsSet && reason.Value == null)
                throw new JsonException("Property is not nullable for class LockdownResult: reason.");

            if (verdict.IsSet && verdict.Value == null)
                throw new JsonException("Property is not nullable for class LockdownResult: verdict.");

            return new LockdownResult(reason, verdict);
        }

        /// <summary>
        /// Serializes a <see cref="LockdownResult" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="lockdownResult"></param>
        /// <param name="jsonSerializerOptions"></param>
        public override void Write(Utf8JsonWriter writer, LockdownResult lockdownResult, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, lockdownResult, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="LockdownResult" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="lockdownResult"></param>
        /// <param name="jsonSerializerOptions"></param>
        public void WriteProperties(Utf8JsonWriter writer, LockdownResult lockdownResult, JsonSerializerOptions jsonSerializerOptions)
        {
            if (lockdownResult.ReasonOption.IsSet && lockdownResult.Reason == null)
                throw new JsonException("Cannot write null property LockdownResult.Reason to non-nullable JSON property 'reason'.");

            if (lockdownResult.VerdictOption.IsSet && lockdownResult.Verdict == null)
                throw new JsonException("Cannot write null property LockdownResult.Verdict to non-nullable JSON property 'verdict'.");

            if (lockdownResult.ReasonOption.IsSet)
                writer.WriteString("reason", lockdownResult.Reason);

            if (lockdownResult.VerdictOption.IsSet)
            {
                var verdictRawValue = LockdownResult.VerdictEnumToJsonValue(lockdownResult.Verdict);
                writer.WriteString("verdict", verdictRawValue);
            }
        }
    }
}
