// <auto-generated>
/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MailChannels.EmailApi.Client;

namespace MailChannels.EmailApi.Model
{
    /// <summary>
    /// Settings to customize the unsubscribe experience for the message. 
    /// </summary>
    public partial class MailSendBodyUnsubscribeSettings : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MailSendBodyUnsubscribeSettings" /> class.
        /// </summary>
        /// <param name="customDomainName">The name of a configured active unsubscribe tracking domain. When specified, unsubscribe links will use this domain instead of the default MailChannels domain. The domain must be registered in your account and have an active status. </param>
        [JsonConstructor]
        public MailSendBodyUnsubscribeSettings(Option<string?> customDomainName = default)
        {
            CustomDomainNameOption = customDomainName;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of CustomDomainName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CustomDomainNameOption { get; private set; }

        /// <summary>
        /// The name of a configured active unsubscribe tracking domain. When specified, unsubscribe links will use this domain instead of the default MailChannels domain. The domain must be registered in your account and have an active status. 
        /// </summary>
        /// <value>The name of a configured active unsubscribe tracking domain. When specified, unsubscribe links will use this domain instead of the default MailChannels domain. The domain must be registered in your account and have an active status. </value>
        [JsonPropertyName("custom_domain_name")]
        public string? CustomDomainName { get { return this.CustomDomainNameOption.Value; } set { this.CustomDomainNameOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            return "MailSendBodyUnsubscribeSettings { [REDACTED] }";
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // CustomDomainName (string) maxLength
            if (this.CustomDomainName != null && this.CustomDomainName.Length > 64)
            {
                yield return new ValidationResult("Invalid value for CustomDomainName, length must be less than 64.", new [] { "CustomDomainName" });
            }

            if (this.CustomDomainNameOption.Value != null) {
                // CustomDomainName (string) pattern
                Regex regexCustomDomainName = new Regex(@"^[a-z0-9-]+$", RegexOptions.CultureInvariant);

                if (this.CustomDomainNameOption.Value != null &&!regexCustomDomainName.Match(this.CustomDomainNameOption.Value).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for CustomDomainName, must match a pattern of " + regexCustomDomainName, new [] { "CustomDomainName" });
                }
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="MailSendBodyUnsubscribeSettings" />
    /// </summary>
    public partial class MailSendBodyUnsubscribeSettingsJsonConverter : JsonConverter<MailSendBodyUnsubscribeSettings>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="MailSendBodyUnsubscribeSettingsJsonConverter" /> class.
        /// </summary>
        public MailSendBodyUnsubscribeSettingsJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="MailSendBodyUnsubscribeSettings" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override MailSendBodyUnsubscribeSettings Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> customDomainName = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "custom_domain_name":
                            customDomainName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (customDomainName.IsSet && customDomainName.Value == null)
                throw new JsonException("Property is not nullable for class MailSendBodyUnsubscribeSettings: custom_domain_name.");

            return new MailSendBodyUnsubscribeSettings(customDomainName);
        }

        /// <summary>
        /// Serializes a <see cref="MailSendBodyUnsubscribeSettings" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="mailSendBodyUnsubscribeSettings"></param>
        /// <param name="jsonSerializerOptions"></param>
        public override void Write(Utf8JsonWriter writer, MailSendBodyUnsubscribeSettings mailSendBodyUnsubscribeSettings, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, mailSendBodyUnsubscribeSettings, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="MailSendBodyUnsubscribeSettings" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="mailSendBodyUnsubscribeSettings"></param>
        /// <param name="jsonSerializerOptions"></param>
        public void WriteProperties(Utf8JsonWriter writer, MailSendBodyUnsubscribeSettings mailSendBodyUnsubscribeSettings, JsonSerializerOptions jsonSerializerOptions)
        {
            if (mailSendBodyUnsubscribeSettings.CustomDomainNameOption.IsSet && mailSendBodyUnsubscribeSettings.CustomDomainName == null)
                throw new JsonException("Cannot write null property MailSendBodyUnsubscribeSettings.CustomDomainName to non-nullable JSON property 'custom_domain_name'.");

            if (mailSendBodyUnsubscribeSettings.CustomDomainNameOption.IsSet)
                writer.WriteString("custom_domain_name", mailSendBodyUnsubscribeSettings.CustomDomainName);
        }
    }
}
