// <auto-generated>
/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MailChannels.EmailApi.Client;

namespace MailChannels.EmailApi.Model
{
    /// <summary>
    /// MetricsPerformance
    /// </summary>
    public partial class MetricsPerformance : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MetricsPerformance" /> class.
        /// </summary>
        /// <param name="bounced">Count of messages hard-bounced during the specified time range. </param>
        /// <param name="buckets">buckets</param>
        /// <param name="complained">Count of messages complained during the specified time range. </param>
        /// <param name="delivered">Count of messages delivered during the specified time range. </param>
        /// <param name="processed">Count of messages processed during the specified time range. </param>
        /// <param name="endTime">The end of the time range for retrieving message performance metrics (exclusive).</param>
        /// <param name="startTime">The beginning of the time range for retrieving message performance metrics (inclusive). </param>
        [JsonConstructor]
        public MetricsPerformance(int bounced, MetricsPerformanceBuckets buckets, int complained, int delivered, int processed, Option<DateTime?> endTime = default, Option<DateTime?> startTime = default)
        {
            Bounced = bounced;
            Buckets = buckets;
            Complained = complained;
            Delivered = delivered;
            Processed = processed;
            EndTimeOption = endTime;
            StartTimeOption = startTime;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Count of messages hard-bounced during the specified time range. 
        /// </summary>
        /// <value>Count of messages hard-bounced during the specified time range. </value>
        [JsonPropertyName("bounced")]
        public int Bounced { get; set; }

        /// <summary>
        /// Gets or Sets Buckets
        /// </summary>
        [JsonPropertyName("buckets")]
        public MetricsPerformanceBuckets Buckets { get; set; }

        /// <summary>
        /// Count of messages complained during the specified time range. 
        /// </summary>
        /// <value>Count of messages complained during the specified time range. </value>
        [JsonPropertyName("complained")]
        public int Complained { get; set; }

        /// <summary>
        /// Count of messages delivered during the specified time range. 
        /// </summary>
        /// <value>Count of messages delivered during the specified time range. </value>
        [JsonPropertyName("delivered")]
        public int Delivered { get; set; }

        /// <summary>
        /// Count of messages processed during the specified time range. 
        /// </summary>
        /// <value>Count of messages processed during the specified time range. </value>
        [JsonPropertyName("processed")]
        public int Processed { get; set; }

        /// <summary>
        /// Used to track the state of EndTime
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> EndTimeOption { get; private set; }

        /// <summary>
        /// The end of the time range for retrieving message performance metrics (exclusive).
        /// </summary>
        /// <value>The end of the time range for retrieving message performance metrics (exclusive).</value>
        [JsonPropertyName("end_time")]
        public DateTime? EndTime { get { return this.EndTimeOption.Value; } set { this.EndTimeOption = new(value); } }

        /// <summary>
        /// Used to track the state of StartTime
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> StartTimeOption { get; private set; }

        /// <summary>
        /// The beginning of the time range for retrieving message performance metrics (inclusive). 
        /// </summary>
        /// <value>The beginning of the time range for retrieving message performance metrics (inclusive). </value>
        [JsonPropertyName("start_time")]
        public DateTime? StartTime { get { return this.StartTimeOption.Value; } set { this.StartTimeOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            return "MetricsPerformance { [REDACTED] }";
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Bounced (int) minimum
            if (this.Bounced < (int)0)
            {
                yield return new ValidationResult("Invalid value for Bounced, must be a value greater than or equal to 0.", new [] { "Bounced" });
            }

            // Complained (int) minimum
            if (this.Complained < (int)0)
            {
                yield return new ValidationResult("Invalid value for Complained, must be a value greater than or equal to 0.", new [] { "Complained" });
            }

            // Delivered (int) minimum
            if (this.Delivered < (int)0)
            {
                yield return new ValidationResult("Invalid value for Delivered, must be a value greater than or equal to 0.", new [] { "Delivered" });
            }

            // Processed (int) minimum
            if (this.Processed < (int)0)
            {
                yield return new ValidationResult("Invalid value for Processed, must be a value greater than or equal to 0.", new [] { "Processed" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="MetricsPerformance" />
    /// </summary>
    public partial class MetricsPerformanceJsonConverter : JsonConverter<MetricsPerformance>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="MetricsPerformanceJsonConverter" /> class.
        /// </summary>
        public MetricsPerformanceJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize EndTime
        /// </summary>
        public string EndTimeFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize StartTime
        /// </summary>
        public string StartTimeFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="MetricsPerformance" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override MetricsPerformance Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> bounced = default;
            Option<MetricsPerformanceBuckets?> buckets = default;
            Option<int?> complained = default;
            Option<int?> delivered = default;
            Option<int?> processed = default;
            Option<DateTime?> endTime = default;
            Option<DateTime?> startTime = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "bounced":
                            bounced = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "buckets":
                            buckets = new Option<MetricsPerformanceBuckets?>(JsonSerializer.Deserialize<MetricsPerformanceBuckets>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "complained":
                            complained = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "delivered":
                            delivered = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "processed":
                            processed = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "end_time":
                            endTime = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "start_time":
                            startTime = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!bounced.IsSet)
                throw new JsonException("Property is required for class MetricsPerformance: bounced.");

            if (!buckets.IsSet)
                throw new JsonException("Property is required for class MetricsPerformance: buckets.");

            if (!complained.IsSet)
                throw new JsonException("Property is required for class MetricsPerformance: complained.");

            if (!delivered.IsSet)
                throw new JsonException("Property is required for class MetricsPerformance: delivered.");

            if (!processed.IsSet)
                throw new JsonException("Property is required for class MetricsPerformance: processed.");

            if (bounced.IsSet && bounced.Value == null)
                throw new JsonException("Property is not nullable for class MetricsPerformance: bounced.");

            if (buckets.IsSet && buckets.Value == null)
                throw new JsonException("Property is not nullable for class MetricsPerformance: buckets.");

            if (complained.IsSet && complained.Value == null)
                throw new JsonException("Property is not nullable for class MetricsPerformance: complained.");

            if (delivered.IsSet && delivered.Value == null)
                throw new JsonException("Property is not nullable for class MetricsPerformance: delivered.");

            if (processed.IsSet && processed.Value == null)
                throw new JsonException("Property is not nullable for class MetricsPerformance: processed.");

            if (endTime.IsSet && endTime.Value == null)
                throw new JsonException("Property is not nullable for class MetricsPerformance: end_time.");

            if (startTime.IsSet && startTime.Value == null)
                throw new JsonException("Property is not nullable for class MetricsPerformance: start_time.");

            return new MetricsPerformance(bounced.Value!.Value!, buckets.Value!, complained.Value!.Value!, delivered.Value!.Value!, processed.Value!.Value!, endTime, startTime);
        }

        /// <summary>
        /// Serializes a <see cref="MetricsPerformance" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="metricsPerformance"></param>
        /// <param name="jsonSerializerOptions"></param>
        public override void Write(Utf8JsonWriter writer, MetricsPerformance metricsPerformance, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, metricsPerformance, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="MetricsPerformance" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="metricsPerformance"></param>
        /// <param name="jsonSerializerOptions"></param>
        public void WriteProperties(Utf8JsonWriter writer, MetricsPerformance metricsPerformance, JsonSerializerOptions jsonSerializerOptions)
        {
            if (metricsPerformance.EndTimeOption.IsSet && metricsPerformance.EndTime == null)
                throw new JsonException("Cannot write null property MetricsPerformance.EndTime to non-nullable JSON property 'end_time'.");

            if (metricsPerformance.StartTimeOption.IsSet && metricsPerformance.StartTime == null)
                throw new JsonException("Cannot write null property MetricsPerformance.StartTime to non-nullable JSON property 'start_time'.");

            writer.WriteNumber("bounced", metricsPerformance.Bounced);

            writer.WritePropertyName("buckets");
            JsonSerializer.Serialize(writer, metricsPerformance.Buckets, jsonSerializerOptions);
            writer.WriteNumber("complained", metricsPerformance.Complained);

            writer.WriteNumber("delivered", metricsPerformance.Delivered);

            writer.WriteNumber("processed", metricsPerformance.Processed);

            if (metricsPerformance.EndTimeOption.IsSet)
                writer.WriteString("end_time", metricsPerformance.EndTimeOption.Value!.Value.ToString(EndTimeFormat));

            if (metricsPerformance.StartTimeOption.IsSet)
                writer.WriteString("start_time", metricsPerformance.StartTimeOption.Value!.Value.ToString(StartTimeFormat));
        }
    }
}
