// <auto-generated>
/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MailChannels.EmailApi.Client;

namespace MailChannels.EmailApi.Model
{
    /// <summary>
    /// MetricsSender
    /// </summary>
    public partial class MetricsSender : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MetricsSender" /> class.
        /// </summary>
        /// <param name="bounced">bounced</param>
        /// <param name="delivered">delivered</param>
        /// <param name="dropped">dropped</param>
        /// <param name="name">name</param>
        /// <param name="processed">processed</param>
        [JsonConstructor]
        public MetricsSender(int bounced, int delivered, int dropped, string name, int processed)
        {
            Bounced = bounced;
            Delivered = delivered;
            Dropped = dropped;
            Name = name;
            Processed = processed;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Bounced
        /// </summary>
        [JsonPropertyName("bounced")]
        public int Bounced { get; set; }

        /// <summary>
        /// Gets or Sets Delivered
        /// </summary>
        [JsonPropertyName("delivered")]
        public int Delivered { get; set; }

        /// <summary>
        /// Gets or Sets Dropped
        /// </summary>
        [JsonPropertyName("dropped")]
        public int Dropped { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Processed
        /// </summary>
        [JsonPropertyName("processed")]
        public int Processed { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            return "MetricsSender { [REDACTED] }";
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Bounced (int) minimum
            if (this.Bounced < (int)0)
            {
                yield return new ValidationResult("Invalid value for Bounced, must be a value greater than or equal to 0.", new [] { "Bounced" });
            }

            // Delivered (int) minimum
            if (this.Delivered < (int)0)
            {
                yield return new ValidationResult("Invalid value for Delivered, must be a value greater than or equal to 0.", new [] { "Delivered" });
            }

            // Dropped (int) minimum
            if (this.Dropped < (int)0)
            {
                yield return new ValidationResult("Invalid value for Dropped, must be a value greater than or equal to 0.", new [] { "Dropped" });
            }

            // Name (string) maxLength
            if (this.Name != null && this.Name.Length > 255)
            {
                yield return new ValidationResult("Invalid value for Name, length must be less than 255.", new [] { "Name" });
            }

            // Processed (int) minimum
            if (this.Processed < (int)0)
            {
                yield return new ValidationResult("Invalid value for Processed, must be a value greater than or equal to 0.", new [] { "Processed" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="MetricsSender" />
    /// </summary>
    public partial class MetricsSenderJsonConverter : JsonConverter<MetricsSender>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="MetricsSenderJsonConverter" /> class.
        /// </summary>
        public MetricsSenderJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="MetricsSender" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override MetricsSender Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> bounced = default;
            Option<int?> delivered = default;
            Option<int?> dropped = default;
            Option<string?> name = default;
            Option<int?> processed = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "bounced":
                            bounced = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "delivered":
                            delivered = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "dropped":
                            dropped = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "processed":
                            processed = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!bounced.IsSet)
                throw new JsonException("Property is required for class MetricsSender: bounced.");

            if (!delivered.IsSet)
                throw new JsonException("Property is required for class MetricsSender: delivered.");

            if (!dropped.IsSet)
                throw new JsonException("Property is required for class MetricsSender: dropped.");

            if (!name.IsSet)
                throw new JsonException("Property is required for class MetricsSender: name.");

            if (!processed.IsSet)
                throw new JsonException("Property is required for class MetricsSender: processed.");

            if (bounced.IsSet && bounced.Value == null)
                throw new JsonException("Property is not nullable for class MetricsSender: bounced.");

            if (delivered.IsSet && delivered.Value == null)
                throw new JsonException("Property is not nullable for class MetricsSender: delivered.");

            if (dropped.IsSet && dropped.Value == null)
                throw new JsonException("Property is not nullable for class MetricsSender: dropped.");

            if (name.IsSet && name.Value == null)
                throw new JsonException("Property is not nullable for class MetricsSender: name.");

            if (processed.IsSet && processed.Value == null)
                throw new JsonException("Property is not nullable for class MetricsSender: processed.");

            return new MetricsSender(bounced.Value!.Value!, delivered.Value!.Value!, dropped.Value!.Value!, name.Value!, processed.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="MetricsSender" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="metricsSender"></param>
        /// <param name="jsonSerializerOptions"></param>
        public override void Write(Utf8JsonWriter writer, MetricsSender metricsSender, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, metricsSender, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="MetricsSender" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="metricsSender"></param>
        /// <param name="jsonSerializerOptions"></param>
        public void WriteProperties(Utf8JsonWriter writer, MetricsSender metricsSender, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteNumber("bounced", metricsSender.Bounced);

            writer.WriteNumber("delivered", metricsSender.Delivered);

            writer.WriteNumber("dropped", metricsSender.Dropped);

            writer.WriteString("name", metricsSender.Name);

            writer.WriteNumber("processed", metricsSender.Processed);
        }
    }
}
