// <auto-generated>
/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MailChannels.EmailApi.Client;

namespace MailChannels.EmailApi.Model
{
    /// <summary>
    /// Represents a time-based bucket for aggregating metrics data. Each bucket corresponds to a specific time interval, with the &#x60;period_start&#x60; indicating the beginning of that interval. The &#x60;count&#x60; field represents the number of events or occurrences that fall within that time period. 
    /// </summary>
    public partial class MetricsBucket : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MetricsBucket" /> class.
        /// </summary>
        /// <param name="count">The number of events or occurrences aggregated within this time period.</param>
        /// <param name="periodStart">The starting date and time of the time period this bucket represents.</param>
        [JsonConstructor]
        public MetricsBucket(int count, DateTime periodStart)
        {
            Count = count;
            PeriodStart = periodStart;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The number of events or occurrences aggregated within this time period.
        /// </summary>
        /// <value>The number of events or occurrences aggregated within this time period.</value>
        [JsonPropertyName("count")]
        public int Count { get; set; }

        /// <summary>
        /// The starting date and time of the time period this bucket represents.
        /// </summary>
        /// <value>The starting date and time of the time period this bucket represents.</value>
        [JsonPropertyName("period_start")]
        public DateTime PeriodStart { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            return "MetricsBucket { [REDACTED] }";
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Count (int) minimum
            if (this.Count < (int)0)
            {
                yield return new ValidationResult("Invalid value for Count, must be a value greater than or equal to 0.", new [] { "Count" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="MetricsBucket" />
    /// </summary>
    public partial class MetricsBucketJsonConverter : JsonConverter<MetricsBucket>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="MetricsBucketJsonConverter" /> class.
        /// </summary>
        public MetricsBucketJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize PeriodStart
        /// </summary>
        public string PeriodStartFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="MetricsBucket" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override MetricsBucket Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> count = default;
            Option<DateTime?> periodStart = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "count":
                            count = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "period_start":
                            periodStart = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!count.IsSet)
                throw new JsonException("Property is required for class MetricsBucket: count.");

            if (!periodStart.IsSet)
                throw new JsonException("Property is required for class MetricsBucket: period_start.");

            if (count.IsSet && count.Value == null)
                throw new JsonException("Property is not nullable for class MetricsBucket: count.");

            if (periodStart.IsSet && periodStart.Value == null)
                throw new JsonException("Property is not nullable for class MetricsBucket: period_start.");

            return new MetricsBucket(count.Value!.Value!, periodStart.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="MetricsBucket" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="metricsBucket"></param>
        /// <param name="jsonSerializerOptions"></param>
        public override void Write(Utf8JsonWriter writer, MetricsBucket metricsBucket, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, metricsBucket, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="MetricsBucket" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="metricsBucket"></param>
        /// <param name="jsonSerializerOptions"></param>
        public void WriteProperties(Utf8JsonWriter writer, MetricsBucket metricsBucket, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteNumber("count", metricsBucket.Count);

            writer.WriteString("period_start", metricsBucket.PeriodStart.ToString(PeriodStartFormat));
        }
    }
}
