// <auto-generated>
/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MailChannels.EmailApi.Client;

namespace MailChannels.EmailApi.Model
{
    /// <summary>
    /// A series of metrics aggregations bucketed by time interval (e.g. hour, day)
    /// </summary>
    public partial class MetricsEngagementBuckets : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MetricsEngagementBuckets" /> class.
        /// </summary>
        /// <param name="click">click</param>
        /// <param name="clickTrackingDelivered">clickTrackingDelivered</param>
        /// <param name="open">open</param>
        /// <param name="openTrackingDelivered">openTrackingDelivered</param>
        /// <param name="uniqueClick">uniqueClick</param>
        /// <param name="uniqueClickTrackingDelivered">uniqueClickTrackingDelivered</param>
        /// <param name="uniqueOpen">uniqueOpen</param>
        /// <param name="uniqueOpenTrackingDelivered">uniqueOpenTrackingDelivered</param>
        [JsonConstructor]
        public MetricsEngagementBuckets(List<MetricsBucket> click, List<MetricsBucket> clickTrackingDelivered, List<MetricsBucket> open, List<MetricsBucket> openTrackingDelivered, Option<List<MetricsBucket>?> uniqueClick = default, Option<List<MetricsBucket>?> uniqueClickTrackingDelivered = default, Option<List<MetricsBucket>?> uniqueOpen = default, Option<List<MetricsBucket>?> uniqueOpenTrackingDelivered = default)
        {
            Click = click;
            ClickTrackingDelivered = clickTrackingDelivered;
            Open = open;
            OpenTrackingDelivered = openTrackingDelivered;
            UniqueClickOption = uniqueClick;
            UniqueClickTrackingDeliveredOption = uniqueClickTrackingDelivered;
            UniqueOpenOption = uniqueOpen;
            UniqueOpenTrackingDeliveredOption = uniqueOpenTrackingDelivered;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Click
        /// </summary>
        [JsonPropertyName("click")]
        public List<MetricsBucket> Click { get; set; }

        /// <summary>
        /// Gets or Sets ClickTrackingDelivered
        /// </summary>
        [JsonPropertyName("click_tracking_delivered")]
        public List<MetricsBucket> ClickTrackingDelivered { get; set; }

        /// <summary>
        /// Gets or Sets Open
        /// </summary>
        [JsonPropertyName("open")]
        public List<MetricsBucket> Open { get; set; }

        /// <summary>
        /// Gets or Sets OpenTrackingDelivered
        /// </summary>
        [JsonPropertyName("open_tracking_delivered")]
        public List<MetricsBucket> OpenTrackingDelivered { get; set; }

        /// <summary>
        /// Used to track the state of UniqueClick
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<MetricsBucket>?> UniqueClickOption { get; private set; }

        /// <summary>
        /// Gets or Sets UniqueClick
        /// </summary>
        [JsonPropertyName("unique_click")]
        public List<MetricsBucket>? UniqueClick { get { return this.UniqueClickOption.Value; } set { this.UniqueClickOption = new(value); } }

        /// <summary>
        /// Used to track the state of UniqueClickTrackingDelivered
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<MetricsBucket>?> UniqueClickTrackingDeliveredOption { get; private set; }

        /// <summary>
        /// Gets or Sets UniqueClickTrackingDelivered
        /// </summary>
        [JsonPropertyName("unique_click_tracking_delivered")]
        public List<MetricsBucket>? UniqueClickTrackingDelivered { get { return this.UniqueClickTrackingDeliveredOption.Value; } set { this.UniqueClickTrackingDeliveredOption = new(value); } }

        /// <summary>
        /// Used to track the state of UniqueOpen
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<MetricsBucket>?> UniqueOpenOption { get; private set; }

        /// <summary>
        /// Gets or Sets UniqueOpen
        /// </summary>
        [JsonPropertyName("unique_open")]
        public List<MetricsBucket>? UniqueOpen { get { return this.UniqueOpenOption.Value; } set { this.UniqueOpenOption = new(value); } }

        /// <summary>
        /// Used to track the state of UniqueOpenTrackingDelivered
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<MetricsBucket>?> UniqueOpenTrackingDeliveredOption { get; private set; }

        /// <summary>
        /// Gets or Sets UniqueOpenTrackingDelivered
        /// </summary>
        [JsonPropertyName("unique_open_tracking_delivered")]
        public List<MetricsBucket>? UniqueOpenTrackingDelivered { get { return this.UniqueOpenTrackingDeliveredOption.Value; } set { this.UniqueOpenTrackingDeliveredOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            return "MetricsEngagementBuckets { [REDACTED] }";
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="MetricsEngagementBuckets" />
    /// </summary>
    public partial class MetricsEngagementBucketsJsonConverter : JsonConverter<MetricsEngagementBuckets>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="MetricsEngagementBucketsJsonConverter" /> class.
        /// </summary>
        public MetricsEngagementBucketsJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="MetricsEngagementBuckets" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override MetricsEngagementBuckets Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<MetricsBucket>?> click = default;
            Option<List<MetricsBucket>?> clickTrackingDelivered = default;
            Option<List<MetricsBucket>?> open = default;
            Option<List<MetricsBucket>?> openTrackingDelivered = default;
            Option<List<MetricsBucket>?> uniqueClick = default;
            Option<List<MetricsBucket>?> uniqueClickTrackingDelivered = default;
            Option<List<MetricsBucket>?> uniqueOpen = default;
            Option<List<MetricsBucket>?> uniqueOpenTrackingDelivered = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "click":
                            click = new Option<List<MetricsBucket>?>(JsonSerializer.Deserialize<List<MetricsBucket>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "click_tracking_delivered":
                            clickTrackingDelivered = new Option<List<MetricsBucket>?>(JsonSerializer.Deserialize<List<MetricsBucket>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "open":
                            open = new Option<List<MetricsBucket>?>(JsonSerializer.Deserialize<List<MetricsBucket>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "open_tracking_delivered":
                            openTrackingDelivered = new Option<List<MetricsBucket>?>(JsonSerializer.Deserialize<List<MetricsBucket>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "unique_click":
                            uniqueClick = new Option<List<MetricsBucket>?>(JsonSerializer.Deserialize<List<MetricsBucket>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "unique_click_tracking_delivered":
                            uniqueClickTrackingDelivered = new Option<List<MetricsBucket>?>(JsonSerializer.Deserialize<List<MetricsBucket>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "unique_open":
                            uniqueOpen = new Option<List<MetricsBucket>?>(JsonSerializer.Deserialize<List<MetricsBucket>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "unique_open_tracking_delivered":
                            uniqueOpenTrackingDelivered = new Option<List<MetricsBucket>?>(JsonSerializer.Deserialize<List<MetricsBucket>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!click.IsSet)
                throw new JsonException("Property is required for class MetricsEngagementBuckets: click.");

            if (!clickTrackingDelivered.IsSet)
                throw new JsonException("Property is required for class MetricsEngagementBuckets: click_tracking_delivered.");

            if (!open.IsSet)
                throw new JsonException("Property is required for class MetricsEngagementBuckets: open.");

            if (!openTrackingDelivered.IsSet)
                throw new JsonException("Property is required for class MetricsEngagementBuckets: open_tracking_delivered.");

            if (click.IsSet && click.Value == null)
                throw new JsonException("Property is not nullable for class MetricsEngagementBuckets: click.");

            if (clickTrackingDelivered.IsSet && clickTrackingDelivered.Value == null)
                throw new JsonException("Property is not nullable for class MetricsEngagementBuckets: click_tracking_delivered.");

            if (open.IsSet && open.Value == null)
                throw new JsonException("Property is not nullable for class MetricsEngagementBuckets: open.");

            if (openTrackingDelivered.IsSet && openTrackingDelivered.Value == null)
                throw new JsonException("Property is not nullable for class MetricsEngagementBuckets: open_tracking_delivered.");

            if (uniqueClick.IsSet && uniqueClick.Value == null)
                throw new JsonException("Property is not nullable for class MetricsEngagementBuckets: unique_click.");

            if (uniqueClickTrackingDelivered.IsSet && uniqueClickTrackingDelivered.Value == null)
                throw new JsonException("Property is not nullable for class MetricsEngagementBuckets: unique_click_tracking_delivered.");

            if (uniqueOpen.IsSet && uniqueOpen.Value == null)
                throw new JsonException("Property is not nullable for class MetricsEngagementBuckets: unique_open.");

            if (uniqueOpenTrackingDelivered.IsSet && uniqueOpenTrackingDelivered.Value == null)
                throw new JsonException("Property is not nullable for class MetricsEngagementBuckets: unique_open_tracking_delivered.");

            return new MetricsEngagementBuckets(click.Value!, clickTrackingDelivered.Value!, open.Value!, openTrackingDelivered.Value!, uniqueClick, uniqueClickTrackingDelivered, uniqueOpen, uniqueOpenTrackingDelivered);
        }

        /// <summary>
        /// Serializes a <see cref="MetricsEngagementBuckets" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="metricsEngagementBuckets"></param>
        /// <param name="jsonSerializerOptions"></param>
        public override void Write(Utf8JsonWriter writer, MetricsEngagementBuckets metricsEngagementBuckets, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, metricsEngagementBuckets, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="MetricsEngagementBuckets" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="metricsEngagementBuckets"></param>
        /// <param name="jsonSerializerOptions"></param>
        public void WriteProperties(Utf8JsonWriter writer, MetricsEngagementBuckets metricsEngagementBuckets, JsonSerializerOptions jsonSerializerOptions)
        {
            if (metricsEngagementBuckets.UniqueClickOption.IsSet && metricsEngagementBuckets.UniqueClick == null)
                throw new JsonException("Cannot write null property MetricsEngagementBuckets.UniqueClick to non-nullable JSON property 'unique_click'.");

            if (metricsEngagementBuckets.UniqueClickTrackingDeliveredOption.IsSet && metricsEngagementBuckets.UniqueClickTrackingDelivered == null)
                throw new JsonException("Cannot write null property MetricsEngagementBuckets.UniqueClickTrackingDelivered to non-nullable JSON property 'unique_click_tracking_delivered'.");

            if (metricsEngagementBuckets.UniqueOpenOption.IsSet && metricsEngagementBuckets.UniqueOpen == null)
                throw new JsonException("Cannot write null property MetricsEngagementBuckets.UniqueOpen to non-nullable JSON property 'unique_open'.");

            if (metricsEngagementBuckets.UniqueOpenTrackingDeliveredOption.IsSet && metricsEngagementBuckets.UniqueOpenTrackingDelivered == null)
                throw new JsonException("Cannot write null property MetricsEngagementBuckets.UniqueOpenTrackingDelivered to non-nullable JSON property 'unique_open_tracking_delivered'.");

            writer.WritePropertyName("click");
            JsonSerializer.Serialize(writer, metricsEngagementBuckets.Click, jsonSerializerOptions);
            writer.WritePropertyName("click_tracking_delivered");
            JsonSerializer.Serialize(writer, metricsEngagementBuckets.ClickTrackingDelivered, jsonSerializerOptions);
            writer.WritePropertyName("open");
            JsonSerializer.Serialize(writer, metricsEngagementBuckets.Open, jsonSerializerOptions);
            writer.WritePropertyName("open_tracking_delivered");
            JsonSerializer.Serialize(writer, metricsEngagementBuckets.OpenTrackingDelivered, jsonSerializerOptions);
            if (metricsEngagementBuckets.UniqueClickOption.IsSet)
            {
                writer.WritePropertyName("unique_click");
                JsonSerializer.Serialize(writer, metricsEngagementBuckets.UniqueClick, jsonSerializerOptions);
            }
            if (metricsEngagementBuckets.UniqueClickTrackingDeliveredOption.IsSet)
            {
                writer.WritePropertyName("unique_click_tracking_delivered");
                JsonSerializer.Serialize(writer, metricsEngagementBuckets.UniqueClickTrackingDelivered, jsonSerializerOptions);
            }
            if (metricsEngagementBuckets.UniqueOpenOption.IsSet)
            {
                writer.WritePropertyName("unique_open");
                JsonSerializer.Serialize(writer, metricsEngagementBuckets.UniqueOpen, jsonSerializerOptions);
            }
            if (metricsEngagementBuckets.UniqueOpenTrackingDeliveredOption.IsSet)
            {
                writer.WritePropertyName("unique_open_tracking_delivered");
                JsonSerializer.Serialize(writer, metricsEngagementBuckets.UniqueOpenTrackingDelivered, jsonSerializerOptions);
            }
        }
    }
}
