// <auto-generated>
/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MailChannels.EmailApi.Client;

namespace MailChannels.EmailApi.Model
{
    /// <summary>
    /// MetricsVolume
    /// </summary>
    public partial class MetricsVolume : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MetricsVolume" /> class.
        /// </summary>
        /// <param name="buckets">buckets</param>
        /// <param name="delivered">Count of messages delivered during the specified time range. </param>
        /// <param name="dropped">Count of messages dropped during the specified time range. </param>
        /// <param name="processed">Count of messages processed during the specified time range. </param>
        /// <param name="endTime">The end of the time range for retrieving message volume metrics (exclusive). </param>
        /// <param name="startTime">The beginning of the time range for retrieving message volume metrics (inclusive). </param>
        [JsonConstructor]
        public MetricsVolume(MetricsVolumeBuckets buckets, int delivered, int dropped, int processed, Option<DateTime?> endTime = default, Option<DateTime?> startTime = default)
        {
            Buckets = buckets;
            Delivered = delivered;
            Dropped = dropped;
            Processed = processed;
            EndTimeOption = endTime;
            StartTimeOption = startTime;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Buckets
        /// </summary>
        [JsonPropertyName("buckets")]
        public MetricsVolumeBuckets Buckets { get; set; }

        /// <summary>
        /// Count of messages delivered during the specified time range. 
        /// </summary>
        /// <value>Count of messages delivered during the specified time range. </value>
        [JsonPropertyName("delivered")]
        public int Delivered { get; set; }

        /// <summary>
        /// Count of messages dropped during the specified time range. 
        /// </summary>
        /// <value>Count of messages dropped during the specified time range. </value>
        [JsonPropertyName("dropped")]
        public int Dropped { get; set; }

        /// <summary>
        /// Count of messages processed during the specified time range. 
        /// </summary>
        /// <value>Count of messages processed during the specified time range. </value>
        [JsonPropertyName("processed")]
        public int Processed { get; set; }

        /// <summary>
        /// Used to track the state of EndTime
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> EndTimeOption { get; private set; }

        /// <summary>
        /// The end of the time range for retrieving message volume metrics (exclusive). 
        /// </summary>
        /// <value>The end of the time range for retrieving message volume metrics (exclusive). </value>
        [JsonPropertyName("end_time")]
        public DateTime? EndTime { get { return this.EndTimeOption.Value; } set { this.EndTimeOption = new(value); } }

        /// <summary>
        /// Used to track the state of StartTime
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> StartTimeOption { get; private set; }

        /// <summary>
        /// The beginning of the time range for retrieving message volume metrics (inclusive). 
        /// </summary>
        /// <value>The beginning of the time range for retrieving message volume metrics (inclusive). </value>
        [JsonPropertyName("start_time")]
        public DateTime? StartTime { get { return this.StartTimeOption.Value; } set { this.StartTimeOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            return "MetricsVolume { [REDACTED] }";
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Delivered (int) minimum
            if (this.Delivered < (int)0)
            {
                yield return new ValidationResult("Invalid value for Delivered, must be a value greater than or equal to 0.", new [] { "Delivered" });
            }

            // Dropped (int) minimum
            if (this.Dropped < (int)0)
            {
                yield return new ValidationResult("Invalid value for Dropped, must be a value greater than or equal to 0.", new [] { "Dropped" });
            }

            // Processed (int) minimum
            if (this.Processed < (int)0)
            {
                yield return new ValidationResult("Invalid value for Processed, must be a value greater than or equal to 0.", new [] { "Processed" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="MetricsVolume" />
    /// </summary>
    public partial class MetricsVolumeJsonConverter : JsonConverter<MetricsVolume>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="MetricsVolumeJsonConverter" /> class.
        /// </summary>
        public MetricsVolumeJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize EndTime
        /// </summary>
        public string EndTimeFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize StartTime
        /// </summary>
        public string StartTimeFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="MetricsVolume" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override MetricsVolume Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<MetricsVolumeBuckets?> buckets = default;
            Option<int?> delivered = default;
            Option<int?> dropped = default;
            Option<int?> processed = default;
            Option<DateTime?> endTime = default;
            Option<DateTime?> startTime = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "buckets":
                            buckets = new Option<MetricsVolumeBuckets?>(JsonSerializer.Deserialize<MetricsVolumeBuckets>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "delivered":
                            delivered = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "dropped":
                            dropped = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "processed":
                            processed = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "end_time":
                            endTime = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "start_time":
                            startTime = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!buckets.IsSet)
                throw new JsonException("Property is required for class MetricsVolume: buckets.");

            if (!delivered.IsSet)
                throw new JsonException("Property is required for class MetricsVolume: delivered.");

            if (!dropped.IsSet)
                throw new JsonException("Property is required for class MetricsVolume: dropped.");

            if (!processed.IsSet)
                throw new JsonException("Property is required for class MetricsVolume: processed.");

            if (buckets.IsSet && buckets.Value == null)
                throw new JsonException("Property is not nullable for class MetricsVolume: buckets.");

            if (delivered.IsSet && delivered.Value == null)
                throw new JsonException("Property is not nullable for class MetricsVolume: delivered.");

            if (dropped.IsSet && dropped.Value == null)
                throw new JsonException("Property is not nullable for class MetricsVolume: dropped.");

            if (processed.IsSet && processed.Value == null)
                throw new JsonException("Property is not nullable for class MetricsVolume: processed.");

            if (endTime.IsSet && endTime.Value == null)
                throw new JsonException("Property is not nullable for class MetricsVolume: end_time.");

            if (startTime.IsSet && startTime.Value == null)
                throw new JsonException("Property is not nullable for class MetricsVolume: start_time.");

            return new MetricsVolume(buckets.Value!, delivered.Value!.Value!, dropped.Value!.Value!, processed.Value!.Value!, endTime, startTime);
        }

        /// <summary>
        /// Serializes a <see cref="MetricsVolume" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="metricsVolume"></param>
        /// <param name="jsonSerializerOptions"></param>
        public override void Write(Utf8JsonWriter writer, MetricsVolume metricsVolume, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, metricsVolume, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="MetricsVolume" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="metricsVolume"></param>
        /// <param name="jsonSerializerOptions"></param>
        public void WriteProperties(Utf8JsonWriter writer, MetricsVolume metricsVolume, JsonSerializerOptions jsonSerializerOptions)
        {
            if (metricsVolume.EndTimeOption.IsSet && metricsVolume.EndTime == null)
                throw new JsonException("Cannot write null property MetricsVolume.EndTime to non-nullable JSON property 'end_time'.");

            if (metricsVolume.StartTimeOption.IsSet && metricsVolume.StartTime == null)
                throw new JsonException("Cannot write null property MetricsVolume.StartTime to non-nullable JSON property 'start_time'.");

            writer.WritePropertyName("buckets");
            JsonSerializer.Serialize(writer, metricsVolume.Buckets, jsonSerializerOptions);
            writer.WriteNumber("delivered", metricsVolume.Delivered);

            writer.WriteNumber("dropped", metricsVolume.Dropped);

            writer.WriteNumber("processed", metricsVolume.Processed);

            if (metricsVolume.EndTimeOption.IsSet)
                writer.WriteString("end_time", metricsVolume.EndTimeOption.Value!.Value.ToString(EndTimeFormat));

            if (metricsVolume.StartTimeOption.IsSet)
                writer.WriteString("start_time", metricsVolume.StartTimeOption.Value!.Value.ToString(StartTimeFormat));
        }
    }
}
