// <auto-generated>
/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MailChannels.EmailApi.Client;

namespace MailChannels.EmailApi.Model
{
    /// <summary>
    /// A series of metrics aggregations bucketed by time interval (e.g. hour, day)
    /// </summary>
    public partial class MetricsVolumeBuckets : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MetricsVolumeBuckets" /> class.
        /// </summary>
        /// <param name="delivered">delivered</param>
        /// <param name="dropped">dropped</param>
        /// <param name="processed">processed</param>
        [JsonConstructor]
        public MetricsVolumeBuckets(List<MetricsBucket> delivered, List<MetricsBucket> dropped, List<MetricsBucket> processed)
        {
            Delivered = delivered;
            Dropped = dropped;
            Processed = processed;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Delivered
        /// </summary>
        [JsonPropertyName("delivered")]
        public List<MetricsBucket> Delivered { get; set; }

        /// <summary>
        /// Gets or Sets Dropped
        /// </summary>
        [JsonPropertyName("dropped")]
        public List<MetricsBucket> Dropped { get; set; }

        /// <summary>
        /// Gets or Sets Processed
        /// </summary>
        [JsonPropertyName("processed")]
        public List<MetricsBucket> Processed { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            return "MetricsVolumeBuckets { [REDACTED] }";
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="MetricsVolumeBuckets" />
    /// </summary>
    public partial class MetricsVolumeBucketsJsonConverter : JsonConverter<MetricsVolumeBuckets>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="MetricsVolumeBucketsJsonConverter" /> class.
        /// </summary>
        public MetricsVolumeBucketsJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="MetricsVolumeBuckets" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override MetricsVolumeBuckets Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<MetricsBucket>?> delivered = default;
            Option<List<MetricsBucket>?> dropped = default;
            Option<List<MetricsBucket>?> processed = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "delivered":
                            delivered = new Option<List<MetricsBucket>?>(JsonSerializer.Deserialize<List<MetricsBucket>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "dropped":
                            dropped = new Option<List<MetricsBucket>?>(JsonSerializer.Deserialize<List<MetricsBucket>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "processed":
                            processed = new Option<List<MetricsBucket>?>(JsonSerializer.Deserialize<List<MetricsBucket>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!delivered.IsSet)
                throw new JsonException("Property is required for class MetricsVolumeBuckets: delivered.");

            if (!dropped.IsSet)
                throw new JsonException("Property is required for class MetricsVolumeBuckets: dropped.");

            if (!processed.IsSet)
                throw new JsonException("Property is required for class MetricsVolumeBuckets: processed.");

            if (delivered.IsSet && delivered.Value == null)
                throw new JsonException("Property is not nullable for class MetricsVolumeBuckets: delivered.");

            if (dropped.IsSet && dropped.Value == null)
                throw new JsonException("Property is not nullable for class MetricsVolumeBuckets: dropped.");

            if (processed.IsSet && processed.Value == null)
                throw new JsonException("Property is not nullable for class MetricsVolumeBuckets: processed.");

            return new MetricsVolumeBuckets(delivered.Value!, dropped.Value!, processed.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="MetricsVolumeBuckets" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="metricsVolumeBuckets"></param>
        /// <param name="jsonSerializerOptions"></param>
        public override void Write(Utf8JsonWriter writer, MetricsVolumeBuckets metricsVolumeBuckets, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, metricsVolumeBuckets, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="MetricsVolumeBuckets" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="metricsVolumeBuckets"></param>
        /// <param name="jsonSerializerOptions"></param>
        public void WriteProperties(Utf8JsonWriter writer, MetricsVolumeBuckets metricsVolumeBuckets, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WritePropertyName("delivered");
            JsonSerializer.Serialize(writer, metricsVolumeBuckets.Delivered, jsonSerializerOptions);
            writer.WritePropertyName("dropped");
            JsonSerializer.Serialize(writer, metricsVolumeBuckets.Dropped, jsonSerializerOptions);
            writer.WritePropertyName("processed");
            JsonSerializer.Serialize(writer, metricsVolumeBuckets.Processed, jsonSerializerOptions);
        }
    }
}
