// <auto-generated>
/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MailChannels.EmailApi.Client;

namespace MailChannels.EmailApi.Model
{
    /// <summary>
    /// MetricsSenderResponse
    /// </summary>
    public partial class MetricsSenderResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MetricsSenderResponse" /> class.
        /// </summary>
        /// <param name="limit">limit</param>
        /// <param name="offset">offset</param>
        /// <param name="senders">senders</param>
        /// <param name="total">The total number of senders in this category that sent messages in the given time range. </param>
        /// <param name="endTime">endTime</param>
        /// <param name="startTime">startTime</param>
        [JsonConstructor]
        public MetricsSenderResponse(int limit, int offset, List<MetricsSender> senders, int total, Option<DateTime?> endTime = default, Option<DateTime?> startTime = default)
        {
            Limit = limit;
            Offset = offset;
            Senders = senders;
            Total = total;
            EndTimeOption = endTime;
            StartTimeOption = startTime;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Limit
        /// </summary>
        [JsonPropertyName("limit")]
        public int Limit { get; set; }

        /// <summary>
        /// Gets or Sets Offset
        /// </summary>
        [JsonPropertyName("offset")]
        public int Offset { get; set; }

        /// <summary>
        /// Gets or Sets Senders
        /// </summary>
        [JsonPropertyName("senders")]
        public List<MetricsSender> Senders { get; set; }

        /// <summary>
        /// The total number of senders in this category that sent messages in the given time range. 
        /// </summary>
        /// <value>The total number of senders in this category that sent messages in the given time range. </value>
        [JsonPropertyName("total")]
        public int Total { get; set; }

        /// <summary>
        /// Used to track the state of EndTime
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> EndTimeOption { get; private set; }

        /// <summary>
        /// Gets or Sets EndTime
        /// </summary>
        [JsonPropertyName("end_time")]
        public DateTime? EndTime { get { return this.EndTimeOption.Value; } set { this.EndTimeOption = new(value); } }

        /// <summary>
        /// Used to track the state of StartTime
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> StartTimeOption { get; private set; }

        /// <summary>
        /// Gets or Sets StartTime
        /// </summary>
        [JsonPropertyName("start_time")]
        public DateTime? StartTime { get { return this.StartTimeOption.Value; } set { this.StartTimeOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            return "MetricsSenderResponse { [REDACTED] }";
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="MetricsSenderResponse" />
    /// </summary>
    public partial class MetricsSenderResponseJsonConverter : JsonConverter<MetricsSenderResponse>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="MetricsSenderResponseJsonConverter" /> class.
        /// </summary>
        public MetricsSenderResponseJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize EndTime
        /// </summary>
        public string EndTimeFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize StartTime
        /// </summary>
        public string StartTimeFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="MetricsSenderResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override MetricsSenderResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> limit = default;
            Option<int?> offset = default;
            Option<List<MetricsSender>?> senders = default;
            Option<int?> total = default;
            Option<DateTime?> endTime = default;
            Option<DateTime?> startTime = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "limit":
                            limit = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "offset":
                            offset = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "senders":
                            senders = new Option<List<MetricsSender>?>(JsonSerializer.Deserialize<List<MetricsSender>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "total":
                            total = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "end_time":
                            endTime = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "start_time":
                            startTime = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!limit.IsSet)
                throw new JsonException("Property is required for class MetricsSenderResponse: limit.");

            if (!offset.IsSet)
                throw new JsonException("Property is required for class MetricsSenderResponse: offset.");

            if (!senders.IsSet)
                throw new JsonException("Property is required for class MetricsSenderResponse: senders.");

            if (!total.IsSet)
                throw new JsonException("Property is required for class MetricsSenderResponse: total.");

            if (limit.IsSet && limit.Value == null)
                throw new JsonException("Property is not nullable for class MetricsSenderResponse: limit.");

            if (offset.IsSet && offset.Value == null)
                throw new JsonException("Property is not nullable for class MetricsSenderResponse: offset.");

            if (senders.IsSet && senders.Value == null)
                throw new JsonException("Property is not nullable for class MetricsSenderResponse: senders.");

            if (total.IsSet && total.Value == null)
                throw new JsonException("Property is not nullable for class MetricsSenderResponse: total.");

            if (endTime.IsSet && endTime.Value == null)
                throw new JsonException("Property is not nullable for class MetricsSenderResponse: end_time.");

            if (startTime.IsSet && startTime.Value == null)
                throw new JsonException("Property is not nullable for class MetricsSenderResponse: start_time.");

            return new MetricsSenderResponse(limit.Value!.Value!, offset.Value!.Value!, senders.Value!, total.Value!.Value!, endTime, startTime);
        }

        /// <summary>
        /// Serializes a <see cref="MetricsSenderResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="metricsSenderResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        public override void Write(Utf8JsonWriter writer, MetricsSenderResponse metricsSenderResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, metricsSenderResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="MetricsSenderResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="metricsSenderResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        public void WriteProperties(Utf8JsonWriter writer, MetricsSenderResponse metricsSenderResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (metricsSenderResponse.EndTimeOption.IsSet && metricsSenderResponse.EndTime == null)
                throw new JsonException("Cannot write null property MetricsSenderResponse.EndTime to non-nullable JSON property 'end_time'.");

            if (metricsSenderResponse.StartTimeOption.IsSet && metricsSenderResponse.StartTime == null)
                throw new JsonException("Cannot write null property MetricsSenderResponse.StartTime to non-nullable JSON property 'start_time'.");

            writer.WriteNumber("limit", metricsSenderResponse.Limit);

            writer.WriteNumber("offset", metricsSenderResponse.Offset);

            writer.WritePropertyName("senders");
            JsonSerializer.Serialize(writer, metricsSenderResponse.Senders, jsonSerializerOptions);
            writer.WriteNumber("total", metricsSenderResponse.Total);

            if (metricsSenderResponse.EndTimeOption.IsSet)
                writer.WriteString("end_time", metricsSenderResponse.EndTimeOption.Value!.Value.ToString(EndTimeFormat));

            if (metricsSenderResponse.StartTimeOption.IsSet)
                writer.WriteString("start_time", metricsSenderResponse.StartTimeOption.Value!.Value.ToString(StartTimeFormat));
        }
    }
}
