// <auto-generated>
/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MailChannels.EmailApi.Client;

namespace MailChannels.EmailApi.Model
{
    /// <summary>
    /// NewKey
    /// </summary>
    public partial class NewKey : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NewKey" /> class.
        /// </summary>
        /// <param name="selector">Selector for the new key pair</param>
        [JsonConstructor]
        public NewKey(string selector)
        {
            Selector = selector;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Selector for the new key pair
        /// </summary>
        /// <value>Selector for the new key pair</value>
        [JsonPropertyName("selector")]
        public string Selector { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            return "NewKey { [REDACTED] }";
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Selector (string) maxLength
            if (this.Selector != null && this.Selector.Length > 63)
            {
                yield return new ValidationResult("Invalid value for Selector, length must be less than 63.", new [] { "Selector" });
            }

            // Selector (string) minLength
            if (this.Selector != null && this.Selector.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Selector, length must be greater than 1.", new [] { "Selector" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="NewKey" />
    /// </summary>
    public partial class NewKeyJsonConverter : JsonConverter<NewKey>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="NewKeyJsonConverter" /> class.
        /// </summary>
        public NewKeyJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="NewKey" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override NewKey Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> selector = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "selector":
                            selector = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!selector.IsSet)
                throw new JsonException("Property is required for class NewKey: selector.");

            if (selector.IsSet && selector.Value == null)
                throw new JsonException("Property is not nullable for class NewKey: selector.");

            return new NewKey(selector.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="NewKey" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="newKey"></param>
        /// <param name="jsonSerializerOptions"></param>
        public override void Write(Utf8JsonWriter writer, NewKey newKey, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, newKey, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="NewKey" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="newKey"></param>
        /// <param name="jsonSerializerOptions"></param>
        public void WriteProperties(Utf8JsonWriter writer, NewKey newKey, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteString("selector", newKey.Selector);
        }
    }
}
