// <auto-generated>
/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MailChannels.EmailApi.Client;

namespace MailChannels.EmailApi.Model
{
    /// <summary>
    /// PatchCustomTrackingDomainRequest
    /// </summary>
    public partial class PatchCustomTrackingDomainRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PatchCustomTrackingDomainRequest" /> class.
        /// </summary>
        /// <param name="name">New label for this custom tracking domain</param>
        /// <param name="status">New status; active ↔ disabled</param>
        [JsonConstructor]
        public PatchCustomTrackingDomainRequest(Option<string?> name = default, Option<StatusEnum?> status = default)
        {
            NameOption = name;
            StatusOption = status;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// New status; active ↔ disabled
        /// </summary>
        /// <value>New status; active ↔ disabled</value>
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Active for value: active
            /// </summary>
            Active = 1,

            /// <summary>
            /// Enum Disabled for value: disabled
            /// </summary>
            Disabled = 2
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static StatusEnum StatusEnumFromString(string value)
        {
            if (value.Equals("active"))
                return StatusEnum.Active;

            if (value.Equals("disabled"))
                return StatusEnum.Disabled;

            throw new NotImplementedException($"Could not convert value to type StatusEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static StatusEnum? StatusEnumFromStringOrDefault(string value)
        {
            if (value.Equals("active"))
                return StatusEnum.Active;

            if (value.Equals("disabled"))
                return StatusEnum.Disabled;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="StatusEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string StatusEnumToJsonValue(StatusEnum? value)
        {
            if (value == StatusEnum.Active)
                return "active";

            if (value == StatusEnum.Disabled)
                return "disabled";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Status
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<StatusEnum?> StatusOption { get; private set; }

        /// <summary>
        /// New status; active ↔ disabled
        /// </summary>
        /// <value>New status; active ↔ disabled</value>
        [JsonPropertyName("status")]
        public StatusEnum? Status { get { return this.StatusOption.Value; } set { this.StatusOption = new(value); } }

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// New label for this custom tracking domain
        /// </summary>
        /// <value>New label for this custom tracking domain</value>
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption.Value; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            return "PatchCustomTrackingDomainRequest { [REDACTED] }";
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Name (string) maxLength
            if (this.Name != null && this.Name.Length > 64)
            {
                yield return new ValidationResult("Invalid value for Name, length must be less than 64.", new [] { "Name" });
            }

            if (this.NameOption.Value != null) {
                // Name (string) pattern
                Regex regexName = new Regex(@"^[a-z0-9-]+$", RegexOptions.CultureInvariant);

                if (this.NameOption.Value != null &&!regexName.Match(this.NameOption.Value).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Name, must match a pattern of " + regexName, new [] { "Name" });
                }
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PatchCustomTrackingDomainRequest" />
    /// </summary>
    public partial class PatchCustomTrackingDomainRequestJsonConverter : JsonConverter<PatchCustomTrackingDomainRequest>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="PatchCustomTrackingDomainRequestJsonConverter" /> class.
        /// </summary>
        public PatchCustomTrackingDomainRequestJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="PatchCustomTrackingDomainRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PatchCustomTrackingDomainRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> name = default;
            Option<PatchCustomTrackingDomainRequest.StatusEnum?> status = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "status":
                            string? statusRawValue = utf8JsonReader.GetString();
                            if (statusRawValue != null)
                            {
                                PatchCustomTrackingDomainRequest.StatusEnum? statusValue = PatchCustomTrackingDomainRequest.StatusEnumFromStringOrDefault(statusRawValue);
                                if (statusValue == null)
                                    throw new JsonException();
                                status = new Option<PatchCustomTrackingDomainRequest.StatusEnum?>(statusValue);
                            }
                            break;
                        default:
                            break;
                    }
                }
            }

            if (name.IsSet && name.Value == null)
                throw new JsonException("Property is not nullable for class PatchCustomTrackingDomainRequest: name.");

            if (status.IsSet && status.Value == null)
                throw new JsonException("Property is not nullable for class PatchCustomTrackingDomainRequest: status.");

            return new PatchCustomTrackingDomainRequest(name, status);
        }

        /// <summary>
        /// Serializes a <see cref="PatchCustomTrackingDomainRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="patchCustomTrackingDomainRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        public override void Write(Utf8JsonWriter writer, PatchCustomTrackingDomainRequest patchCustomTrackingDomainRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, patchCustomTrackingDomainRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PatchCustomTrackingDomainRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="patchCustomTrackingDomainRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        public void WriteProperties(Utf8JsonWriter writer, PatchCustomTrackingDomainRequest patchCustomTrackingDomainRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (patchCustomTrackingDomainRequest.NameOption.IsSet && patchCustomTrackingDomainRequest.Name == null)
                throw new JsonException("Cannot write null property PatchCustomTrackingDomainRequest.Name to non-nullable JSON property 'name'.");

            if (patchCustomTrackingDomainRequest.StatusOption.IsSet && patchCustomTrackingDomainRequest.Status == null)
                throw new JsonException("Cannot write null property PatchCustomTrackingDomainRequest.Status to non-nullable JSON property 'status'.");

            if (patchCustomTrackingDomainRequest.NameOption.IsSet)
                writer.WriteString("name", patchCustomTrackingDomainRequest.Name);

            if (patchCustomTrackingDomainRequest.StatusOption.IsSet)
            {
                var statusRawValue = PatchCustomTrackingDomainRequest.StatusEnumToJsonValue(patchCustomTrackingDomainRequest.Status);
                writer.WriteString("status", statusRawValue);
            }
        }
    }
}
