// <auto-generated>
/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MailChannels.EmailApi.Client;

namespace MailChannels.EmailApi.Model
{
    /// <summary>
    /// These results are here to help avoid SDNF (Sender Domain Not Found) blocks. For messages not to get blocked by [SDNF](https://support.mailchannels.com/hc/en-us/articles/203155500-550-5-2-1-SDNF-Sender-Domain-Not-Found), we require either an MX or A record to exist for the sender domain. 
    /// </summary>
    public partial class SenderDomainResult : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SenderDomainResult" /> class.
        /// </summary>
        /// <param name="a">a</param>
        /// <param name="mx">mx</param>
        /// <param name="verdict">Overall verdict. Passed if either A or MX record check passed.</param>
        [JsonConstructor]
        public SenderDomainResult(Option<SenderDomainResultA?> a = default, Option<SenderDomainResultMx?> mx = default, Option<VerdictEnum?> verdict = default)
        {
            AOption = a;
            MxOption = mx;
            VerdictOption = verdict;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Overall verdict. Passed if either A or MX record check passed.
        /// </summary>
        /// <value>Overall verdict. Passed if either A or MX record check passed.</value>
        public enum VerdictEnum
        {
            /// <summary>
            /// Enum Passed for value: passed
            /// </summary>
            Passed = 1,

            /// <summary>
            /// Enum Failed for value: failed
            /// </summary>
            Failed = 2
        }

        /// <summary>
        /// Returns a <see cref="VerdictEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static VerdictEnum VerdictEnumFromString(string value)
        {
            if (value.Equals("passed"))
                return VerdictEnum.Passed;

            if (value.Equals("failed"))
                return VerdictEnum.Failed;

            throw new NotImplementedException($"Could not convert value to type VerdictEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="VerdictEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static VerdictEnum? VerdictEnumFromStringOrDefault(string value)
        {
            if (value.Equals("passed"))
                return VerdictEnum.Passed;

            if (value.Equals("failed"))
                return VerdictEnum.Failed;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="VerdictEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string VerdictEnumToJsonValue(VerdictEnum? value)
        {
            if (value == VerdictEnum.Passed)
                return "passed";

            if (value == VerdictEnum.Failed)
                return "failed";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Verdict
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<VerdictEnum?> VerdictOption { get; private set; }

        /// <summary>
        /// Overall verdict. Passed if either A or MX record check passed.
        /// </summary>
        /// <value>Overall verdict. Passed if either A or MX record check passed.</value>
        [JsonPropertyName("verdict")]
        public VerdictEnum? Verdict { get { return this.VerdictOption.Value; } set { this.VerdictOption = new(value); } }

        /// <summary>
        /// Used to track the state of A
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<SenderDomainResultA?> AOption { get; private set; }

        /// <summary>
        /// Gets or Sets A
        /// </summary>
        [JsonPropertyName("a")]
        public SenderDomainResultA? A { get { return this.AOption.Value; } set { this.AOption = new(value); } }

        /// <summary>
        /// Used to track the state of Mx
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<SenderDomainResultMx?> MxOption { get; private set; }

        /// <summary>
        /// Gets or Sets Mx
        /// </summary>
        [JsonPropertyName("mx")]
        public SenderDomainResultMx? Mx { get { return this.MxOption.Value; } set { this.MxOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            return "SenderDomainResult { [REDACTED] }";
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SenderDomainResult" />
    /// </summary>
    public partial class SenderDomainResultJsonConverter : JsonConverter<SenderDomainResult>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="SenderDomainResultJsonConverter" /> class.
        /// </summary>
        public SenderDomainResultJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="SenderDomainResult" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SenderDomainResult Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<SenderDomainResultA?> a = default;
            Option<SenderDomainResultMx?> mx = default;
            Option<SenderDomainResult.VerdictEnum?> verdict = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "a":
                            a = new Option<SenderDomainResultA?>(JsonSerializer.Deserialize<SenderDomainResultA>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "mx":
                            mx = new Option<SenderDomainResultMx?>(JsonSerializer.Deserialize<SenderDomainResultMx>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "verdict":
                            string? verdictRawValue = utf8JsonReader.GetString();
                            if (verdictRawValue != null)
                            {
                                SenderDomainResult.VerdictEnum? verdictValue = SenderDomainResult.VerdictEnumFromStringOrDefault(verdictRawValue);
                                if (verdictValue == null)
                                    throw new JsonException();
                                verdict = new Option<SenderDomainResult.VerdictEnum?>(verdictValue);
                            }
                            break;
                        default:
                            break;
                    }
                }
            }

            if (a.IsSet && a.Value == null)
                throw new JsonException("Property is not nullable for class SenderDomainResult: a.");

            if (mx.IsSet && mx.Value == null)
                throw new JsonException("Property is not nullable for class SenderDomainResult: mx.");

            if (verdict.IsSet && verdict.Value == null)
                throw new JsonException("Property is not nullable for class SenderDomainResult: verdict.");

            return new SenderDomainResult(a, mx, verdict);
        }

        /// <summary>
        /// Serializes a <see cref="SenderDomainResult" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="senderDomainResult"></param>
        /// <param name="jsonSerializerOptions"></param>
        public override void Write(Utf8JsonWriter writer, SenderDomainResult senderDomainResult, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, senderDomainResult, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SenderDomainResult" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="senderDomainResult"></param>
        /// <param name="jsonSerializerOptions"></param>
        public void WriteProperties(Utf8JsonWriter writer, SenderDomainResult senderDomainResult, JsonSerializerOptions jsonSerializerOptions)
        {
            if (senderDomainResult.AOption.IsSet && senderDomainResult.A == null)
                throw new JsonException("Cannot write null property SenderDomainResult.A to non-nullable JSON property 'a'.");

            if (senderDomainResult.MxOption.IsSet && senderDomainResult.Mx == null)
                throw new JsonException("Cannot write null property SenderDomainResult.Mx to non-nullable JSON property 'mx'.");

            if (senderDomainResult.VerdictOption.IsSet && senderDomainResult.Verdict == null)
                throw new JsonException("Cannot write null property SenderDomainResult.Verdict to non-nullable JSON property 'verdict'.");

            if (senderDomainResult.AOption.IsSet)
            {
                writer.WritePropertyName("a");
                JsonSerializer.Serialize(writer, senderDomainResult.A, jsonSerializerOptions);
            }
            if (senderDomainResult.MxOption.IsSet)
            {
                writer.WritePropertyName("mx");
                JsonSerializer.Serialize(writer, senderDomainResult.Mx, jsonSerializerOptions);
            }
            if (senderDomainResult.VerdictOption.IsSet)
            {
                var verdictRawValue = SenderDomainResult.VerdictEnumToJsonValue(senderDomainResult.Verdict);
                writer.WriteString("verdict", verdictRawValue);
            }
        }
    }
}
