// <auto-generated>
/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MailChannels.EmailApi.Client;

namespace MailChannels.EmailApi.Model
{
    /// <summary>
    /// SendResults
    /// </summary>
    public partial class SendResults : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SendResults" /> class.
        /// </summary>
        /// <param name="requestId">The Request ID is a unique identifier generated by the service to track the HTTP request. It will also be included in all webhooks for reference. </param>
        /// <param name="results">A list of results for each message sent. </param>
        [JsonConstructor]
        public SendResults(Option<string?> requestId = default, Option<List<SendResult>?> results = default)
        {
            RequestIdOption = requestId;
            ResultsOption = results;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of RequestId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> RequestIdOption { get; private set; }

        /// <summary>
        /// The Request ID is a unique identifier generated by the service to track the HTTP request. It will also be included in all webhooks for reference. 
        /// </summary>
        /// <value>The Request ID is a unique identifier generated by the service to track the HTTP request. It will also be included in all webhooks for reference. </value>
        [JsonPropertyName("request_id")]
        public string? RequestId { get { return this.RequestIdOption.Value; } set { this.RequestIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Results
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<SendResult>?> ResultsOption { get; private set; }

        /// <summary>
        /// A list of results for each message sent. 
        /// </summary>
        /// <value>A list of results for each message sent. </value>
        [JsonPropertyName("results")]
        public List<SendResult>? Results { get { return this.ResultsOption.Value; } set { this.ResultsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            return "SendResults { [REDACTED] }";
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SendResults" />
    /// </summary>
    public partial class SendResultsJsonConverter : JsonConverter<SendResults>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="SendResultsJsonConverter" /> class.
        /// </summary>
        public SendResultsJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="SendResults" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SendResults Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> requestId = default;
            Option<List<SendResult>?> results = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "request_id":
                            requestId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "results":
                            results = new Option<List<SendResult>?>(JsonSerializer.Deserialize<List<SendResult>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (requestId.IsSet && requestId.Value == null)
                throw new JsonException("Property is not nullable for class SendResults: request_id.");

            if (results.IsSet && results.Value == null)
                throw new JsonException("Property is not nullable for class SendResults: results.");

            return new SendResults(requestId, results);
        }

        /// <summary>
        /// Serializes a <see cref="SendResults" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="sendResults"></param>
        /// <param name="jsonSerializerOptions"></param>
        public override void Write(Utf8JsonWriter writer, SendResults sendResults, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, sendResults, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SendResults" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="sendResults"></param>
        /// <param name="jsonSerializerOptions"></param>
        public void WriteProperties(Utf8JsonWriter writer, SendResults sendResults, JsonSerializerOptions jsonSerializerOptions)
        {
            if (sendResults.RequestIdOption.IsSet && sendResults.RequestId == null)
                throw new JsonException("Cannot write null property SendResults.RequestId to non-nullable JSON property 'request_id'.");

            if (sendResults.ResultsOption.IsSet && sendResults.Results == null)
                throw new JsonException("Cannot write null property SendResults.Results to non-nullable JSON property 'results'.");

            if (sendResults.RequestIdOption.IsSet)
                writer.WriteString("request_id", sendResults.RequestId);

            if (sendResults.ResultsOption.IsSet)
            {
                writer.WritePropertyName("results");
                JsonSerializer.Serialize(writer, sendResults.Results, jsonSerializerOptions);
            }
        }
    }
}
