// <auto-generated>
/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MailChannels.EmailApi.Client;

namespace MailChannels.EmailApi.Model
{
    /// <summary>
    /// SuppressionListResponse
    /// </summary>
    public partial class SuppressionListResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SuppressionListResponse" /> class.
        /// </summary>
        /// <param name="suppressionList">suppressionList</param>
        [JsonConstructor]
        public SuppressionListResponse(List<SuppressionEntryResponse> suppressionList)
        {
            SuppressionList = suppressionList;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets SuppressionList
        /// </summary>
        [JsonPropertyName("suppression_list")]
        public List<SuppressionEntryResponse> SuppressionList { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            return "SuppressionListResponse { [REDACTED] }";
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SuppressionListResponse" />
    /// </summary>
    public partial class SuppressionListResponseJsonConverter : JsonConverter<SuppressionListResponse>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="SuppressionListResponseJsonConverter" /> class.
        /// </summary>
        public SuppressionListResponseJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="SuppressionListResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SuppressionListResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<SuppressionEntryResponse>?> suppressionList = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "suppression_list":
                            suppressionList = new Option<List<SuppressionEntryResponse>?>(JsonSerializer.Deserialize<List<SuppressionEntryResponse>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!suppressionList.IsSet)
                throw new JsonException("Property is required for class SuppressionListResponse: suppression_list.");

            if (suppressionList.IsSet && suppressionList.Value == null)
                throw new JsonException("Property is not nullable for class SuppressionListResponse: suppression_list.");

            return new SuppressionListResponse(suppressionList.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="SuppressionListResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="suppressionListResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        public override void Write(Utf8JsonWriter writer, SuppressionListResponse suppressionListResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, suppressionListResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SuppressionListResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="suppressionListResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        public void WriteProperties(Utf8JsonWriter writer, SuppressionListResponse suppressionListResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WritePropertyName("suppression_list");
            JsonSerializer.Serialize(writer, suppressionListResponse.SuppressionList, jsonSerializerOptions);
        }
    }
}
