// <auto-generated>
/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MailChannels.EmailApi.Client;

namespace MailChannels.EmailApi.Model
{
    /// <summary>
    /// SuppressionEntry
    /// </summary>
    public partial class SuppressionEntry : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SuppressionEntry" /> class.
        /// </summary>
        /// <param name="recipient">recipient</param>
        /// <param name="notes">notes</param>
        /// <param name="suppressionTypes">suppressionTypes</param>
        [JsonConstructor]
        public SuppressionEntry(string recipient, Option<string?> notes = default, Option<List<SuppressionEntry.SuppressionTypesEnum>?> suppressionTypes = default)
        {
            Recipient = recipient;
            NotesOption = notes;
            SuppressionTypesOption = suppressionTypes;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines SuppressionTypes
        /// </summary>
        public enum SuppressionTypesEnum
        {
            /// <summary>
            /// Enum Transactional for value: transactional
            /// </summary>
            Transactional = 1,

            /// <summary>
            /// Enum NonTransactional for value: non-transactional
            /// </summary>
            NonTransactional = 2
        }

        /// <summary>
        /// Returns a <see cref="SuppressionTypesEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static SuppressionTypesEnum SuppressionTypesEnumFromString(string value)
        {
            if (value.Equals("transactional"))
                return SuppressionTypesEnum.Transactional;

            if (value.Equals("non-transactional"))
                return SuppressionTypesEnum.NonTransactional;

            throw new NotImplementedException($"Could not convert value to type SuppressionTypesEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="SuppressionTypesEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static SuppressionTypesEnum? SuppressionTypesEnumFromStringOrDefault(string value)
        {
            if (value.Equals("transactional"))
                return SuppressionTypesEnum.Transactional;

            if (value.Equals("non-transactional"))
                return SuppressionTypesEnum.NonTransactional;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="SuppressionTypesEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string SuppressionTypesEnumToJsonValue(SuppressionTypesEnum? value)
        {
            if (value == SuppressionTypesEnum.Transactional)
                return "transactional";

            if (value == SuppressionTypesEnum.NonTransactional)
                return "non-transactional";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets Recipient
        /// </summary>
        [JsonPropertyName("recipient")]
        public string Recipient { get; set; }

        /// <summary>
        /// Used to track the state of Notes
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NotesOption { get; private set; }

        /// <summary>
        /// Gets or Sets Notes
        /// </summary>
        [JsonPropertyName("notes")]
        public string? Notes { get { return this.NotesOption.Value; } set { this.NotesOption = new(value); } }

        /// <summary>
        /// Used to track the state of SuppressionTypes
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<SuppressionEntry.SuppressionTypesEnum>?> SuppressionTypesOption { get; private set; }

        /// <summary>
        /// Gets or Sets SuppressionTypes
        /// </summary>
        [JsonPropertyName("suppression_types")]
        public List<SuppressionEntry.SuppressionTypesEnum>? SuppressionTypes { get { return this.SuppressionTypesOption.Value; } set { this.SuppressionTypesOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            return "SuppressionEntry { [REDACTED] }";
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Recipient (string) maxLength
            if (this.Recipient != null && this.Recipient.Length > 255)
            {
                yield return new ValidationResult("Invalid value for Recipient, length must be less than 255.", new [] { "Recipient" });
            }

            // Notes (string) maxLength
            if (this.Notes != null && this.Notes.Length > 1024)
            {
                yield return new ValidationResult("Invalid value for Notes, length must be less than 1024.", new [] { "Notes" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SuppressionEntry" />
    /// </summary>
    public partial class SuppressionEntryJsonConverter : JsonConverter<SuppressionEntry>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="SuppressionEntryJsonConverter" /> class.
        /// </summary>
        public SuppressionEntryJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="SuppressionEntry" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SuppressionEntry Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> recipient = default;
            Option<string?> notes = default;
            Option<List<SuppressionEntry.SuppressionTypesEnum>?> suppressionTypes = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "recipient":
                            recipient = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "notes":
                            notes = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "suppression_types":
                            suppressionTypes = new Option<List<SuppressionEntry.SuppressionTypesEnum>?>(JsonSerializer.Deserialize<List<SuppressionEntry.SuppressionTypesEnum>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!recipient.IsSet)
                throw new JsonException("Property is required for class SuppressionEntry: recipient.");

            if (recipient.IsSet && recipient.Value == null)
                throw new JsonException("Property is not nullable for class SuppressionEntry: recipient.");

            if (suppressionTypes.IsSet && suppressionTypes.Value == null)
                throw new JsonException("Property is not nullable for class SuppressionEntry: suppression_types.");

            return new SuppressionEntry(recipient.Value!, notes, suppressionTypes);
        }

        /// <summary>
        /// Serializes a <see cref="SuppressionEntry" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="suppressionEntry"></param>
        /// <param name="jsonSerializerOptions"></param>
        public override void Write(Utf8JsonWriter writer, SuppressionEntry suppressionEntry, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, suppressionEntry, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SuppressionEntry" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="suppressionEntry"></param>
        /// <param name="jsonSerializerOptions"></param>
        public void WriteProperties(Utf8JsonWriter writer, SuppressionEntry suppressionEntry, JsonSerializerOptions jsonSerializerOptions)
        {
            if (suppressionEntry.SuppressionTypesOption.IsSet && suppressionEntry.SuppressionTypes == null)
                throw new JsonException("Cannot write null property SuppressionEntry.SuppressionTypes to non-nullable JSON property 'suppression_types'.");

            writer.WriteString("recipient", suppressionEntry.Recipient);

            if (suppressionEntry.NotesOption.IsSet)
                if (suppressionEntry.NotesOption.Value != null)
                    writer.WriteString("notes", suppressionEntry.Notes);
                else
                    writer.WriteNull("notes");

            if (suppressionEntry.SuppressionTypesOption.IsSet)
            {
                writer.WritePropertyName("suppression_types");
                JsonSerializer.Serialize(writer, suppressionEntry.SuppressionTypes, jsonSerializerOptions);
            }
        }
    }
}
