// <auto-generated>
/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MailChannels.EmailApi.Client;

namespace MailChannels.EmailApi.Model
{
    /// <summary>
    /// SuppressionEntryResponse
    /// </summary>
    public partial class SuppressionEntryResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SuppressionEntryResponse" /> class.
        /// </summary>
        /// <param name="recipient">recipient</param>
        /// <param name="createdAt">createdAt</param>
        /// <param name="notes">notes</param>
        /// <param name="sender">sender</param>
        /// <param name="source">source</param>
        /// <param name="suppressionTypes">suppressionTypes</param>
        [JsonConstructor]
        public SuppressionEntryResponse(string recipient, Option<DateTime?> createdAt = default, Option<string?> notes = default, Option<string?> sender = default, Option<SourceEnum?> source = default, Option<List<SuppressionEntryResponse.SuppressionTypesEnum>?> suppressionTypes = default)
        {
            Recipient = recipient;
            CreatedAtOption = createdAt;
            NotesOption = notes;
            SenderOption = sender;
            SourceOption = source;
            SuppressionTypesOption = suppressionTypes;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Source
        /// </summary>
        public enum SourceEnum
        {
            /// <summary>
            /// Enum Api for value: api
            /// </summary>
            Api = 1,

            /// <summary>
            /// Enum UnsubscribeLink for value: unsubscribe_link
            /// </summary>
            UnsubscribeLink = 2,

            /// <summary>
            /// Enum ListUnsubscribe for value: list_unsubscribe
            /// </summary>
            ListUnsubscribe = 3,

            /// <summary>
            /// Enum HardBounce for value: hard_bounce
            /// </summary>
            HardBounce = 4,

            /// <summary>
            /// Enum SpamComplaint for value: spam_complaint
            /// </summary>
            SpamComplaint = 5
        }

        /// <summary>
        /// Returns a <see cref="SourceEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static SourceEnum SourceEnumFromString(string value)
        {
            if (value.Equals("api"))
                return SourceEnum.Api;

            if (value.Equals("unsubscribe_link"))
                return SourceEnum.UnsubscribeLink;

            if (value.Equals("list_unsubscribe"))
                return SourceEnum.ListUnsubscribe;

            if (value.Equals("hard_bounce"))
                return SourceEnum.HardBounce;

            if (value.Equals("spam_complaint"))
                return SourceEnum.SpamComplaint;

            throw new NotImplementedException($"Could not convert value to type SourceEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="SourceEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static SourceEnum? SourceEnumFromStringOrDefault(string value)
        {
            if (value.Equals("api"))
                return SourceEnum.Api;

            if (value.Equals("unsubscribe_link"))
                return SourceEnum.UnsubscribeLink;

            if (value.Equals("list_unsubscribe"))
                return SourceEnum.ListUnsubscribe;

            if (value.Equals("hard_bounce"))
                return SourceEnum.HardBounce;

            if (value.Equals("spam_complaint"))
                return SourceEnum.SpamComplaint;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="SourceEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string SourceEnumToJsonValue(SourceEnum? value)
        {
            if (value == SourceEnum.Api)
                return "api";

            if (value == SourceEnum.UnsubscribeLink)
                return "unsubscribe_link";

            if (value == SourceEnum.ListUnsubscribe)
                return "list_unsubscribe";

            if (value == SourceEnum.HardBounce)
                return "hard_bounce";

            if (value == SourceEnum.SpamComplaint)
                return "spam_complaint";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Source
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<SourceEnum?> SourceOption { get; private set; }

        /// <summary>
        /// Gets or Sets Source
        /// </summary>
        [JsonPropertyName("source")]
        public SourceEnum? Source { get { return this.SourceOption.Value; } set { this.SourceOption = new(value); } }

        /// <summary>
        /// Defines SuppressionTypes
        /// </summary>
        public enum SuppressionTypesEnum
        {
            /// <summary>
            /// Enum Transactional for value: transactional
            /// </summary>
            Transactional = 1,

            /// <summary>
            /// Enum NonTransactional for value: non-transactional
            /// </summary>
            NonTransactional = 2
        }

        /// <summary>
        /// Returns a <see cref="SuppressionTypesEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static SuppressionTypesEnum SuppressionTypesEnumFromString(string value)
        {
            if (value.Equals("transactional"))
                return SuppressionTypesEnum.Transactional;

            if (value.Equals("non-transactional"))
                return SuppressionTypesEnum.NonTransactional;

            throw new NotImplementedException($"Could not convert value to type SuppressionTypesEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="SuppressionTypesEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static SuppressionTypesEnum? SuppressionTypesEnumFromStringOrDefault(string value)
        {
            if (value.Equals("transactional"))
                return SuppressionTypesEnum.Transactional;

            if (value.Equals("non-transactional"))
                return SuppressionTypesEnum.NonTransactional;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="SuppressionTypesEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string SuppressionTypesEnumToJsonValue(SuppressionTypesEnum? value)
        {
            if (value == SuppressionTypesEnum.Transactional)
                return "transactional";

            if (value == SuppressionTypesEnum.NonTransactional)
                return "non-transactional";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets Recipient
        /// </summary>
        [JsonPropertyName("recipient")]
        public string Recipient { get; set; }

        /// <summary>
        /// Used to track the state of CreatedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> CreatedAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [JsonPropertyName("created_at")]
        public DateTime? CreatedAt { get { return this.CreatedAtOption.Value; } set { this.CreatedAtOption = new(value); } }

        /// <summary>
        /// Used to track the state of Notes
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NotesOption { get; private set; }

        /// <summary>
        /// Gets or Sets Notes
        /// </summary>
        [JsonPropertyName("notes")]
        public string? Notes { get { return this.NotesOption.Value; } set { this.NotesOption = new(value); } }

        /// <summary>
        /// Used to track the state of Sender
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SenderOption { get; private set; }

        /// <summary>
        /// Gets or Sets Sender
        /// </summary>
        [JsonPropertyName("sender")]
        public string? Sender { get { return this.SenderOption.Value; } set { this.SenderOption = new(value); } }

        /// <summary>
        /// Used to track the state of SuppressionTypes
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<SuppressionEntryResponse.SuppressionTypesEnum>?> SuppressionTypesOption { get; private set; }

        /// <summary>
        /// Gets or Sets SuppressionTypes
        /// </summary>
        [JsonPropertyName("suppression_types")]
        public List<SuppressionEntryResponse.SuppressionTypesEnum>? SuppressionTypes { get { return this.SuppressionTypesOption.Value; } set { this.SuppressionTypesOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            return "SuppressionEntryResponse { [REDACTED] }";
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Recipient (string) maxLength
            if (this.Recipient != null && this.Recipient.Length > 255)
            {
                yield return new ValidationResult("Invalid value for Recipient, length must be less than 255.", new [] { "Recipient" });
            }

            // Notes (string) maxLength
            if (this.Notes != null && this.Notes.Length > 1024)
            {
                yield return new ValidationResult("Invalid value for Notes, length must be less than 1024.", new [] { "Notes" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SuppressionEntryResponse" />
    /// </summary>
    public partial class SuppressionEntryResponseJsonConverter : JsonConverter<SuppressionEntryResponse>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="SuppressionEntryResponseJsonConverter" /> class.
        /// </summary>
        public SuppressionEntryResponseJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize CreatedAt
        /// </summary>
        public string CreatedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="SuppressionEntryResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SuppressionEntryResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> recipient = default;
            Option<DateTime?> createdAt = default;
            Option<string?> notes = default;
            Option<string?> sender = default;
            Option<SuppressionEntryResponse.SourceEnum?> source = default;
            Option<List<SuppressionEntryResponse.SuppressionTypesEnum>?> suppressionTypes = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "recipient":
                            recipient = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "created_at":
                            createdAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "notes":
                            notes = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "sender":
                            sender = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "source":
                            string? sourceRawValue = utf8JsonReader.GetString();
                            if (sourceRawValue != null)
                            {
                                SuppressionEntryResponse.SourceEnum? sourceValue = SuppressionEntryResponse.SourceEnumFromStringOrDefault(sourceRawValue);
                                if (sourceValue == null)
                                    throw new JsonException();
                                source = new Option<SuppressionEntryResponse.SourceEnum?>(sourceValue);
                            }
                            break;
                        case "suppression_types":
                            suppressionTypes = new Option<List<SuppressionEntryResponse.SuppressionTypesEnum>?>(JsonSerializer.Deserialize<List<SuppressionEntryResponse.SuppressionTypesEnum>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!recipient.IsSet)
                throw new JsonException("Property is required for class SuppressionEntryResponse: recipient.");

            if (recipient.IsSet && recipient.Value == null)
                throw new JsonException("Property is not nullable for class SuppressionEntryResponse: recipient.");

            if (createdAt.IsSet && createdAt.Value == null)
                throw new JsonException("Property is not nullable for class SuppressionEntryResponse: created_at.");

            if (source.IsSet && source.Value == null)
                throw new JsonException("Property is not nullable for class SuppressionEntryResponse: source.");

            if (suppressionTypes.IsSet && suppressionTypes.Value == null)
                throw new JsonException("Property is not nullable for class SuppressionEntryResponse: suppression_types.");

            return new SuppressionEntryResponse(recipient.Value!, createdAt, notes, sender, source, suppressionTypes);
        }

        /// <summary>
        /// Serializes a <see cref="SuppressionEntryResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="suppressionEntryResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        public override void Write(Utf8JsonWriter writer, SuppressionEntryResponse suppressionEntryResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, suppressionEntryResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SuppressionEntryResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="suppressionEntryResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        public void WriteProperties(Utf8JsonWriter writer, SuppressionEntryResponse suppressionEntryResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (suppressionEntryResponse.CreatedAtOption.IsSet && suppressionEntryResponse.CreatedAt == null)
                throw new JsonException("Cannot write null property SuppressionEntryResponse.CreatedAt to non-nullable JSON property 'created_at'.");

            if (suppressionEntryResponse.SourceOption.IsSet && suppressionEntryResponse.Source == null)
                throw new JsonException("Cannot write null property SuppressionEntryResponse.Source to non-nullable JSON property 'source'.");

            if (suppressionEntryResponse.SuppressionTypesOption.IsSet && suppressionEntryResponse.SuppressionTypes == null)
                throw new JsonException("Cannot write null property SuppressionEntryResponse.SuppressionTypes to non-nullable JSON property 'suppression_types'.");

            writer.WriteString("recipient", suppressionEntryResponse.Recipient);

            if (suppressionEntryResponse.CreatedAtOption.IsSet)
                writer.WriteString("created_at", suppressionEntryResponse.CreatedAtOption.Value!.Value.ToString(CreatedAtFormat));

            if (suppressionEntryResponse.NotesOption.IsSet)
                if (suppressionEntryResponse.NotesOption.Value != null)
                    writer.WriteString("notes", suppressionEntryResponse.Notes);
                else
                    writer.WriteNull("notes");

            if (suppressionEntryResponse.SenderOption.IsSet)
                if (suppressionEntryResponse.SenderOption.Value != null)
                    writer.WriteString("sender", suppressionEntryResponse.Sender);
                else
                    writer.WriteNull("sender");

            if (suppressionEntryResponse.SourceOption.IsSet)
            {
                var sourceRawValue = SuppressionEntryResponse.SourceEnumToJsonValue(suppressionEntryResponse.Source);
                writer.WriteString("source", sourceRawValue);
            }
            if (suppressionEntryResponse.SuppressionTypesOption.IsSet)
            {
                writer.WritePropertyName("suppression_types");
                JsonSerializer.Serialize(writer, suppressionEntryResponse.SuppressionTypes, jsonSerializerOptions);
            }
        }
    }
}
