// <auto-generated>
/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MailChannels.EmailApi.Client;

namespace MailChannels.EmailApi.Model
{
    /// <summary>
    /// UsageStats
    /// </summary>
    public partial class UsageStats : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UsageStats" /> class.
        /// </summary>
        /// <param name="monthlyLimit">The effective monthly limit for the current billing period. A limit of zero means the account cannot send any messages. For sub-accounts with no explicit limit set (i.e., -1), the monthly limit for the parent account is returned. </param>
        /// <param name="totalUsage">The total usage for the current billing period.</param>
        /// <param name="periodEndDate">The end date of the current billing period (ISO 8601 format).</param>
        /// <param name="periodStartDate">The start date of the current billing period (ISO 8601 format).</param>
        [JsonConstructor]
        public UsageStats(int monthlyLimit, long totalUsage, Option<DateOnly?> periodEndDate = default, Option<DateOnly?> periodStartDate = default)
        {
            MonthlyLimit = monthlyLimit;
            TotalUsage = totalUsage;
            PeriodEndDateOption = periodEndDate;
            PeriodStartDateOption = periodStartDate;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The effective monthly limit for the current billing period. A limit of zero means the account cannot send any messages. For sub-accounts with no explicit limit set (i.e., -1), the monthly limit for the parent account is returned. 
        /// </summary>
        /// <value>The effective monthly limit for the current billing period. A limit of zero means the account cannot send any messages. For sub-accounts with no explicit limit set (i.e., -1), the monthly limit for the parent account is returned. </value>
        /* <example>10000</example> */
        [JsonPropertyName("monthly_limit")]
        public int MonthlyLimit { get; set; }

        /// <summary>
        /// The total usage for the current billing period.
        /// </summary>
        /// <value>The total usage for the current billing period.</value>
        /* <example>5000</example> */
        [JsonPropertyName("total_usage")]
        public long TotalUsage { get; set; }

        /// <summary>
        /// Used to track the state of PeriodEndDate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateOnly?> PeriodEndDateOption { get; private set; }

        /// <summary>
        /// The end date of the current billing period (ISO 8601 format).
        /// </summary>
        /// <value>The end date of the current billing period (ISO 8601 format).</value>
        /* <example>Fri Apr 11 00:00:00 UTC 2025</example> */
        [JsonPropertyName("period_end_date")]
        public DateOnly? PeriodEndDate { get { return this.PeriodEndDateOption.Value; } set { this.PeriodEndDateOption = new(value); } }

        /// <summary>
        /// Used to track the state of PeriodStartDate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateOnly?> PeriodStartDateOption { get; private set; }

        /// <summary>
        /// The start date of the current billing period (ISO 8601 format).
        /// </summary>
        /// <value>The start date of the current billing period (ISO 8601 format).</value>
        /* <example>Wed Mar 12 00:00:00 UTC 2025</example> */
        [JsonPropertyName("period_start_date")]
        public DateOnly? PeriodStartDate { get { return this.PeriodStartDateOption.Value; } set { this.PeriodStartDateOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            return "UsageStats { [REDACTED] }";
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="UsageStats" />
    /// </summary>
    public partial class UsageStatsJsonConverter : JsonConverter<UsageStats>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="UsageStatsJsonConverter" /> class.
        /// </summary>
        public UsageStatsJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize PeriodEndDate
        /// </summary>
        public string PeriodEndDateFormat { get; private set; } = "yyyy'-'MM'-'dd";

        /// <summary>
        /// The format to use to serialize PeriodStartDate
        /// </summary>
        public string PeriodStartDateFormat { get; private set; } = "yyyy'-'MM'-'dd";

        /// <summary>
        /// Deserializes json to <see cref="UsageStats" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override UsageStats Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> monthlyLimit = default;
            Option<long?> totalUsage = default;
            Option<DateOnly?> periodEndDate = default;
            Option<DateOnly?> periodStartDate = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "monthly_limit":
                            monthlyLimit = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "total_usage":
                            totalUsage = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "period_end_date":
                            periodEndDate = new Option<DateOnly?>(JsonSerializer.Deserialize<DateOnly>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "period_start_date":
                            periodStartDate = new Option<DateOnly?>(JsonSerializer.Deserialize<DateOnly>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!monthlyLimit.IsSet)
                throw new JsonException("Property is required for class UsageStats: monthly_limit.");

            if (!totalUsage.IsSet)
                throw new JsonException("Property is required for class UsageStats: total_usage.");

            if (monthlyLimit.IsSet && monthlyLimit.Value == null)
                throw new JsonException("Property is not nullable for class UsageStats: monthly_limit.");

            if (totalUsage.IsSet && totalUsage.Value == null)
                throw new JsonException("Property is not nullable for class UsageStats: total_usage.");

            if (periodEndDate.IsSet && periodEndDate.Value == null)
                throw new JsonException("Property is not nullable for class UsageStats: period_end_date.");

            if (periodStartDate.IsSet && periodStartDate.Value == null)
                throw new JsonException("Property is not nullable for class UsageStats: period_start_date.");

            return new UsageStats(monthlyLimit.Value!.Value!, totalUsage.Value!.Value!, periodEndDate, periodStartDate);
        }

        /// <summary>
        /// Serializes a <see cref="UsageStats" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="usageStats"></param>
        /// <param name="jsonSerializerOptions"></param>
        public override void Write(Utf8JsonWriter writer, UsageStats usageStats, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, usageStats, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="UsageStats" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="usageStats"></param>
        /// <param name="jsonSerializerOptions"></param>
        public void WriteProperties(Utf8JsonWriter writer, UsageStats usageStats, JsonSerializerOptions jsonSerializerOptions)
        {
            if (usageStats.PeriodEndDateOption.IsSet && usageStats.PeriodEndDate == null)
                throw new JsonException("Cannot write null property UsageStats.PeriodEndDate to non-nullable JSON property 'period_end_date'.");

            if (usageStats.PeriodStartDateOption.IsSet && usageStats.PeriodStartDate == null)
                throw new JsonException("Cannot write null property UsageStats.PeriodStartDate to non-nullable JSON property 'period_start_date'.");

            writer.WriteNumber("monthly_limit", usageStats.MonthlyLimit);

            writer.WriteNumber("total_usage", usageStats.TotalUsage);

            if (usageStats.PeriodEndDateOption.IsSet)
                writer.WriteString("period_end_date", usageStats.PeriodEndDateOption.Value!.Value.ToString(PeriodEndDateFormat));

            if (usageStats.PeriodStartDateOption.IsSet)
                writer.WriteString("period_start_date", usageStats.PeriodStartDateOption.Value!.Value.ToString(PeriodStartDateFormat));
        }
    }
}
