// <auto-generated>
/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MailChannels.EmailApi.Client;

namespace MailChannels.EmailApi.Model
{
    /// <summary>
    /// WebhookValidationResult
    /// </summary>
    public partial class WebhookValidationResult : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WebhookValidationResult" /> class.
        /// </summary>
        /// <param name="result">Indicates whether the webhook responded with a 2xx HTTP status code </param>
        /// <param name="webhook">The webhook that was validated </param>
        /// <param name="response">response</param>
        [JsonConstructor]
        public WebhookValidationResult(ResultEnum result, string webhook, WebhookResponse? response = default)
        {
            Result = result;
            Webhook = webhook;
            Response = response;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Indicates whether the webhook responded with a 2xx HTTP status code 
        /// </summary>
        /// <value>Indicates whether the webhook responded with a 2xx HTTP status code </value>
        public enum ResultEnum
        {
            /// <summary>
            /// Enum Passed for value: passed
            /// </summary>
            Passed = 1,

            /// <summary>
            /// Enum Failed for value: failed
            /// </summary>
            Failed = 2
        }

        /// <summary>
        /// Returns a <see cref="ResultEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static ResultEnum ResultEnumFromString(string value)
        {
            if (value.Equals("passed"))
                return ResultEnum.Passed;

            if (value.Equals("failed"))
                return ResultEnum.Failed;

            throw new NotImplementedException($"Could not convert value to type ResultEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="ResultEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ResultEnum? ResultEnumFromStringOrDefault(string value)
        {
            if (value.Equals("passed"))
                return ResultEnum.Passed;

            if (value.Equals("failed"))
                return ResultEnum.Failed;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="ResultEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ResultEnumToJsonValue(ResultEnum value)
        {
            if (value == ResultEnum.Passed)
                return "passed";

            if (value == ResultEnum.Failed)
                return "failed";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Indicates whether the webhook responded with a 2xx HTTP status code 
        /// </summary>
        /// <value>Indicates whether the webhook responded with a 2xx HTTP status code </value>
        [JsonPropertyName("result")]
        public ResultEnum Result { get; set; }

        /// <summary>
        /// The webhook that was validated 
        /// </summary>
        /// <value>The webhook that was validated </value>
        [JsonPropertyName("webhook")]
        public string Webhook { get; set; }

        /// <summary>
        /// Gets or Sets Response
        /// </summary>
        [JsonPropertyName("response")]
        public WebhookResponse? Response { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            return "WebhookValidationResult { [REDACTED] }";
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="WebhookValidationResult" />
    /// </summary>
    public partial class WebhookValidationResultJsonConverter : JsonConverter<WebhookValidationResult>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="WebhookValidationResultJsonConverter" /> class.
        /// </summary>
        public WebhookValidationResultJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="WebhookValidationResult" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override WebhookValidationResult Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<WebhookValidationResult.ResultEnum?> result = default;
            Option<string?> webhook = default;
            Option<WebhookResponse?> response = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "result":
                            string? resultRawValue = utf8JsonReader.GetString();
                            if (resultRawValue != null)
                            {
                                WebhookValidationResult.ResultEnum? resultValue = WebhookValidationResult.ResultEnumFromStringOrDefault(resultRawValue);
                                if (resultValue == null)
                                    throw new JsonException();
                                result = new Option<WebhookValidationResult.ResultEnum?>(resultValue);
                            }
                            break;
                        case "webhook":
                            webhook = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "response":
                            response = new Option<WebhookResponse?>(JsonSerializer.Deserialize<WebhookResponse>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!result.IsSet)
                throw new JsonException("Property is required for class WebhookValidationResult: result.");

            if (!webhook.IsSet)
                throw new JsonException("Property is required for class WebhookValidationResult: webhook.");

            if (!response.IsSet)
                throw new JsonException("Property is required for class WebhookValidationResult: response.");

            if (result.IsSet && result.Value == null)
                throw new JsonException("Property is not nullable for class WebhookValidationResult: result.");

            if (webhook.IsSet && webhook.Value == null)
                throw new JsonException("Property is not nullable for class WebhookValidationResult: webhook.");

            return new WebhookValidationResult(result.Value!.Value!, webhook.Value!, response.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="WebhookValidationResult" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="webhookValidationResult"></param>
        /// <param name="jsonSerializerOptions"></param>
        public override void Write(Utf8JsonWriter writer, WebhookValidationResult webhookValidationResult, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, webhookValidationResult, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="WebhookValidationResult" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="webhookValidationResult"></param>
        /// <param name="jsonSerializerOptions"></param>
        public void WriteProperties(Utf8JsonWriter writer, WebhookValidationResult webhookValidationResult, JsonSerializerOptions jsonSerializerOptions)
        {
                var resultRawValue = WebhookValidationResult.ResultEnumToJsonValue(webhookValidationResult.Result);
                writer.WriteString("result", resultRawValue);
            writer.WriteString("webhook", webhookValidationResult.Webhook);

            if (webhookValidationResult.Response != null)
            {
                writer.WritePropertyName("response");
                JsonSerializer.Serialize(writer, webhookValidationResult.Response, jsonSerializerOptions);
            }
            else
                writer.WriteNull("response");
        }
    }
}
