// <auto-generated>
/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MailChannels.EmailApi.Client;

namespace MailChannels.EmailApi.Model
{
    /// <summary>
    /// The HTTP response returned by the webhook, including status code and response body. A null value indicates no response was received. Possible reasons include timeouts, connection failures, or other network-related issues. 
    /// </summary>
    public partial class WebhookResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WebhookResponse" /> class.
        /// </summary>
        /// <param name="status">HTTP status code returned by the webhook </param>
        /// <param name="body">Response body from webhook. Returns an error if unprocessable or too large. </param>
        [JsonConstructor]
        public WebhookResponse(int status, Option<string?> body = default)
        {
            Status = status;
            BodyOption = body;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// HTTP status code returned by the webhook 
        /// </summary>
        /// <value>HTTP status code returned by the webhook </value>
        /* <example>200</example> */
        [JsonPropertyName("status")]
        public int Status { get; set; }

        /// <summary>
        /// Used to track the state of Body
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> BodyOption { get; private set; }

        /// <summary>
        /// Response body from webhook. Returns an error if unprocessable or too large. 
        /// </summary>
        /// <value>Response body from webhook. Returns an error if unprocessable or too large. </value>
        [JsonPropertyName("body")]
        public string? Body { get { return this.BodyOption.Value; } set { this.BodyOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            return "WebhookResponse { [REDACTED] }";
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="WebhookResponse" />
    /// </summary>
    public partial class WebhookResponseJsonConverter : JsonConverter<WebhookResponse>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="WebhookResponseJsonConverter" /> class.
        /// </summary>
        public WebhookResponseJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="WebhookResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override WebhookResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> status = default;
            Option<string?> body = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "status":
                            status = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "body":
                            body = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!status.IsSet)
                throw new JsonException("Property is required for class WebhookResponse: status.");

            if (status.IsSet && status.Value == null)
                throw new JsonException("Property is not nullable for class WebhookResponse: status.");

            if (body.IsSet && body.Value == null)
                throw new JsonException("Property is not nullable for class WebhookResponse: body.");

            return new WebhookResponse(status.Value!.Value!, body);
        }

        /// <summary>
        /// Serializes a <see cref="WebhookResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="webhookResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        public override void Write(Utf8JsonWriter writer, WebhookResponse webhookResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, webhookResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="WebhookResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="webhookResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        public void WriteProperties(Utf8JsonWriter writer, WebhookResponse webhookResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (webhookResponse.BodyOption.IsSet && webhookResponse.Body == null)
                throw new JsonException("Cannot write null property WebhookResponse.Body to non-nullable JSON property 'body'.");

            writer.WriteNumber("status", webhookResponse.Status);

            if (webhookResponse.BodyOption.IsSet)
                writer.WriteString("body", webhookResponse.Body);
        }
    }
}
