// <auto-generated>
/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes. 
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MailChannels.EmailApi.Client;

namespace MailChannels.EmailApi.Model
{
    /// <summary>
    /// WebhookResendResponse
    /// </summary>
    public partial class WebhookResendResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WebhookResendResponse" /> class.
        /// </summary>
        /// <param name="batchId">Unique identifier for the webhook batch </param>
        /// <param name="createdAt">Timestamp of when the webhook batch was created</param>
        /// <param name="customerHandle">Customer handle associated with the webhook batch</param>
        /// <param name="eventCount">Number of events in the webhook batch</param>
        /// <param name="webhook">Webhook URL to which events in the batch were posted</param>
        /// <param name="durationInMs">Duration of the webhook batch in milliseconds, measured from the time the request was sent to the webhook endpoint until the response was received. Null indicates that no response was returned from the webhook endpoint. </param>
        /// <param name="statusCode">HTTP status code returned by the webhook endpoint. Valid values are 100-599. Null indicates that no response was returned from the webhook endpoint. </param>
        [JsonConstructor]
        public WebhookResendResponse(long batchId, DateTime createdAt, string customerHandle, int eventCount, string webhook, Option<int?> durationInMs = default, Option<int?> statusCode = default)
        {
            BatchId = batchId;
            CreatedAt = createdAt;
            CustomerHandle = customerHandle;
            EventCount = eventCount;
            Webhook = webhook;
            DurationInMsOption = durationInMs;
            StatusCodeOption = statusCode;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Unique identifier for the webhook batch 
        /// </summary>
        /// <value>Unique identifier for the webhook batch </value>
        [JsonPropertyName("batch_id")]
        public long BatchId { get; set; }

        /// <summary>
        /// Timestamp of when the webhook batch was created
        /// </summary>
        /// <value>Timestamp of when the webhook batch was created</value>
        [JsonPropertyName("created_at")]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Customer handle associated with the webhook batch
        /// </summary>
        /// <value>Customer handle associated with the webhook batch</value>
        [JsonPropertyName("customer_handle")]
        public string CustomerHandle { get; set; }

        /// <summary>
        /// Number of events in the webhook batch
        /// </summary>
        /// <value>Number of events in the webhook batch</value>
        [JsonPropertyName("event_count")]
        public int EventCount { get; set; }

        /// <summary>
        /// Webhook URL to which events in the batch were posted
        /// </summary>
        /// <value>Webhook URL to which events in the batch were posted</value>
        [JsonPropertyName("webhook")]
        public string Webhook { get; set; }

        /// <summary>
        /// Used to track the state of DurationInMs
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> DurationInMsOption { get; private set; }

        /// <summary>
        /// Duration of the webhook batch in milliseconds, measured from the time the request was sent to the webhook endpoint until the response was received. Null indicates that no response was returned from the webhook endpoint. 
        /// </summary>
        /// <value>Duration of the webhook batch in milliseconds, measured from the time the request was sent to the webhook endpoint until the response was received. Null indicates that no response was returned from the webhook endpoint. </value>
        [JsonPropertyName("duration_in_ms")]
        public int? DurationInMs { get { return this.DurationInMsOption.Value; } set { this.DurationInMsOption = new(value); } }

        /// <summary>
        /// Used to track the state of StatusCode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> StatusCodeOption { get; private set; }

        /// <summary>
        /// HTTP status code returned by the webhook endpoint. Valid values are 100-599. Null indicates that no response was returned from the webhook endpoint. 
        /// </summary>
        /// <value>HTTP status code returned by the webhook endpoint. Valid values are 100-599. Null indicates that no response was returned from the webhook endpoint. </value>
        [JsonPropertyName("status_code")]
        public int? StatusCode { get { return this.StatusCodeOption.Value; } set { this.StatusCodeOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            return "WebhookResendResponse { [REDACTED] }";
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // BatchId (long) minimum
            if (this.BatchId < (long)0)
            {
                yield return new ValidationResult("Invalid value for BatchId, must be a value greater than or equal to 0.", new [] { "BatchId" });
            }

            // CustomerHandle (string) maxLength
            if (this.CustomerHandle != null && this.CustomerHandle.Length > 255)
            {
                yield return new ValidationResult("Invalid value for CustomerHandle, length must be less than 255.", new [] { "CustomerHandle" });
            }

            // EventCount (int) minimum
            if (this.EventCount < (int)0)
            {
                yield return new ValidationResult("Invalid value for EventCount, must be a value greater than or equal to 0.", new [] { "EventCount" });
            }

            // DurationInMs (int) minimum
            if (this.DurationInMsOption.IsSet && this.DurationInMsOption.Value < (int)0)
            {
                yield return new ValidationResult("Invalid value for DurationInMs, must be a value greater than or equal to 0.", new [] { "DurationInMs" });
            }

            // StatusCode (int) maximum
            if (this.StatusCodeOption.IsSet && this.StatusCodeOption.Value > (int)599)
            {
                yield return new ValidationResult("Invalid value for StatusCode, must be a value less than or equal to 599.", new [] { "StatusCode" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="WebhookResendResponse" />
    /// </summary>
    public partial class WebhookResendResponseJsonConverter : JsonConverter<WebhookResendResponse>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="WebhookResendResponseJsonConverter" /> class.
        /// </summary>
        public WebhookResendResponseJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize CreatedAt
        /// </summary>
        public string CreatedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="WebhookResendResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override WebhookResendResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<long?> batchId = default;
            Option<DateTime?> createdAt = default;
            Option<string?> customerHandle = default;
            Option<int?> eventCount = default;
            Option<string?> webhook = default;
            Option<int?> durationInMs = default;
            Option<int?> statusCode = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "batch_id":
                            batchId = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "created_at":
                            createdAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "customer_handle":
                            customerHandle = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "event_count":
                            eventCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "webhook":
                            webhook = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "duration_in_ms":
                            durationInMs = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "status_code":
                            statusCode = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!batchId.IsSet)
                throw new JsonException("Property is required for class WebhookResendResponse: batch_id.");

            if (!createdAt.IsSet)
                throw new JsonException("Property is required for class WebhookResendResponse: created_at.");

            if (!customerHandle.IsSet)
                throw new JsonException("Property is required for class WebhookResendResponse: customer_handle.");

            if (!eventCount.IsSet)
                throw new JsonException("Property is required for class WebhookResendResponse: event_count.");

            if (!webhook.IsSet)
                throw new JsonException("Property is required for class WebhookResendResponse: webhook.");

            if (batchId.IsSet && batchId.Value == null)
                throw new JsonException("Property is not nullable for class WebhookResendResponse: batch_id.");

            if (createdAt.IsSet && createdAt.Value == null)
                throw new JsonException("Property is not nullable for class WebhookResendResponse: created_at.");

            if (customerHandle.IsSet && customerHandle.Value == null)
                throw new JsonException("Property is not nullable for class WebhookResendResponse: customer_handle.");

            if (eventCount.IsSet && eventCount.Value == null)
                throw new JsonException("Property is not nullable for class WebhookResendResponse: event_count.");

            if (webhook.IsSet && webhook.Value == null)
                throw new JsonException("Property is not nullable for class WebhookResendResponse: webhook.");

            return new WebhookResendResponse(batchId.Value!.Value!, createdAt.Value!.Value!, customerHandle.Value!, eventCount.Value!.Value!, webhook.Value!, durationInMs, statusCode);
        }

        /// <summary>
        /// Serializes a <see cref="WebhookResendResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="webhookResendResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        public override void Write(Utf8JsonWriter writer, WebhookResendResponse webhookResendResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, webhookResendResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="WebhookResendResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="webhookResendResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        public void WriteProperties(Utf8JsonWriter writer, WebhookResendResponse webhookResendResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteNumber("batch_id", webhookResendResponse.BatchId);

            writer.WriteString("created_at", webhookResendResponse.CreatedAt.ToString(CreatedAtFormat));

            writer.WriteString("customer_handle", webhookResendResponse.CustomerHandle);

            writer.WriteNumber("event_count", webhookResendResponse.EventCount);

            writer.WriteString("webhook", webhookResendResponse.Webhook);

            if (webhookResendResponse.DurationInMsOption.IsSet)
                if (webhookResendResponse.DurationInMsOption.Value != null)
                    writer.WriteNumber("duration_in_ms", webhookResendResponse.DurationInMsOption.Value!.Value);
                else
                    writer.WriteNull("duration_in_ms");

            if (webhookResendResponse.StatusCodeOption.IsSet)
                if (webhookResendResponse.StatusCodeOption.Value != null)
                    writer.WriteNumber("status_code", webhookResendResponse.StatusCodeOption.Value!.Value);
                else
                    writer.WriteNull("status_code");
        }
    }
}
